#!/usr/bin/env python3
"""Fill batch 64: Troops.json boss-battle dialogue (final major batch)."""
import csv
import os
import re

D = {
"バンデッド": "Bandit",
"ピピンは自らの体に斬りつけた！": "Pipin slashes his own body!",
"ウィンはうなずいた！": "Win nodded!",
"ううおおああアァァー…！！！！": "Uuughaaah...!!!!",
"ナウーは不思議な構えを取った！": "Nau takes a strange stance!",
"ナウーの反撃確率がアップした！": "Nau's counter rate increases!",
"ナウーのぼうぎょ力がアップした！": "Nau's defense increases!",
"ウィンは頷いた！": "Win nodded!",
"刀ってことは…　": "If it has a katana...",
"セイリューに関係する魔物なんじゃねえのか？": "it must be a monster tied to Seiryu, right?",
"分からないよ。": "I don't know.",
"この前に村を襲った魔物もだけど、": "Like the ones that attacked the village before,",
"最近見たこともない魔物ばっかりなのさ。": "lately it's all monsters we've never seen.",
"なんだこの魔物…？": "What are these monsters...?",
"なんか知らんけど、むちゃくちゃカッコいいぞ…": "I don't know why, but they look insanely cool...",
"見たこともない鎧を着ている…": "They're wearing armor we've never seen...",
"でもあいつらが持っているのは、刀だ。": "But what they carry is a katana.",
"こいつはムチでの攻撃も強力だが、": "Its whip attacks are powerful,",
"魔法も使ってくる…　強敵だ。": "and it uses magic too... a formidable foe.",
"こっちも紋章の魔法をフル動員しなければ": "Without throwing all our crest magic into play,",
"勝てないだろう…。": "we probably can't win...",
"みんな、魔法や回復アイテムを忘れるな！！": "Everyone, don't forget magic and recovery items!!",
"おう！　わかったぜ！": "Yeah! Got it!",
"てめえら…　青龍を失っただけでも、": "You lot... losing Seiryu already,",
"こっちはもう後がねえんだ…": "we've got nothing left...",
"遊びは終わりだからなー…": "The games are over now...",
"てめえらの人生も終わりだからなーーーー！！": "And so are your lives—!!",
"おい！　アンタ！": "Hey! You!",
"5ターン以内にオレらを倒すって言ってたよな？": "You said you'd beat us within five turns, right?",
"ああん！！？？？": "Huh!!???",
"やれるもんならやってみろよ！": "Go ahead and try, if you can!",
"セイリューの当主のナガレさーーーーん？": "Nagare, lord of Seiryu~?",
"はい、ナガレです。": "Yes, I'm Nagare.",
"ナガレさんでしたらこの激しいバトルの": "If it's Lady Nagare, even in the middle",
"最中でも、きっとお分かりになると": "of this fierce battle, surely you'd know",
"あれ！？　あれれれれ？？": "Huh!? Wha...??",
"思うんですがー": "don't you think~?",
"いま何ターン経過したでしょうかーーー？": "How many turns have passed by now~?",
"この会話をしている段階でちょうど": "At this very moment in the conversation,",
"6ターンです。": "it's exactly six turns.",
"だとよーーーーーミケーネ！！": "You hear that—!! Mycenae!!",
"えーーーーーい、うるさい！！！！！！": "Bah—! Shut up!!!!!!",
"ほんの少し寿命が延びたことに感謝しろ！！": "Be grateful your lives were extended by a moment!!",
"すぐだ…もうすぐに終わらせてやる…！！！！": "Soon... I'll end this soon...!!!!",
"あ、そう。へへへ…": "Oh, is that so. Hehehe...",
"バー――――――カ！！": "You idiooooot!!",
"あんだあ！？どうしたコラあ！！？？": "What was that!? Say that again!!??",
"ちょっとここで、冷静にバトルを観察するのが": "Let's ask Nagare, who's so good at calmly",
"得意なナガレさんに聞いてみましょう…": "observing a battle...",
"いけっ！　ウィン！！": "Go, Win!!",
"ピピンなんか倒してしまえーい！！": "Knock Pipin out already!!",
"ウィン！　ピピンは操られている！": "Win! Pipin is being controlled!",
"何かがきっかけで正気に戻るかも知れん！": "Something might snap him back to his senses!",
"ウィンは首を横に振った！": "Win shook his head!",
"俺は…天才だ…": "I... am a genius...",
"そう呼ぶのは俺だけじゃない、誰もが認める。": "It's not just me saying it—everyone agrees.",
"そんな俺が、貴様のような新米の小僧に、": "And someone like me had everything taken",
"すべてを奪われた…": "by a rookie brat like you...",
"その理由を、貴様は答えられるのか！？": "Can you tell me why!?",
"ウィンは左手を高くかかげた！": "Win raises his left hand high!",
"ハヤテの魔法が発動！　ウィンの回避力がアップした！": "Hayate activates! Win's evasion increases!",
"ウィン！": "Win!",
"風の紋章の力とお前の素早さがあれば…": "With the Wind Crest's power and your agility...",
"ピピンの攻撃と言えども、": "even Pipin's attacks",
"避け続けることができるはずだ！": "you should be able to keep dodging!",
"避け続けろ！　ウィン！": "Keep dodging! Win!",
"…風の紋章の力か。": "...The Wind Crest's power, is it.",
"…俺から奪ったその力で、俺の攻撃をすべて": "...With the power you stole from me, you mean to",
"避け続けようと言うんだな…　ウィン！！": "dodge all my attacks... don't you, Win!!",
"ウィン…　手を抜いているのか…？": "Win... are you holding back...?",
"ふざけているのか！　ウィン！！": "Are you mocking me! Win!!",
"えーい！　ウィンのやつ…": "Bah! That Win...",
"避けているばかりで、ちっともピピンに": "he's only dodging, not dealing any",
"ダメージを与えられぬではないか！": "damage to Pipin at all!",
"ウィンは気合をこめて斬りかかった！": "Win charges in with all his spirit!",
"…しかし力がはいらない": "...But his strength won't come out.",
"ピピン！！　目を覚ませ！！": "Pipin!! Wake up!!",
"ウィンはお前を殺したくないのだ…": "Win doesn't want to kill you...",
"殺せないのだ……　ピピン…！": "he can't... Pipin...!",
"それが屈辱なんだろう…？": "That's what humiliates you, isn't it...?",
"それが許せないんだよ…": "You can't stand it...",
"俺を憐れむなと言っているだろうがああ！！！": "I told you not to pity me, damn it!!!",
"もうよい！　ピピンを殺せ！": "Enough! Kill Pipin!",
"ウィンにできないのであれば…　我が斬る！！": "If Win cannot... then I shall strike!!",
"な、ななな、なりませぬぞ陛下！！": "N-No, no, no, you mustn't, Your Majesty!!",
"いまのあやつに近付くなど…": "Getting near him now...",
"ウィン以外には不可能です！！": "is impossible for anyone but Win!!",
"サクソン殿の言う通りですぞ、陛下！": "Lord Saxon speaks the truth, Your Majesty!",
"ここは、ウィンに任せてやって下さい！": "Please, leave this to Win!",
"むう…": "Hmm...",
"そんな風に扱われて…　俺が喜ぶと思うのか…": "Do you think I'm pleased... being handled like this...",
"余計に情けなく…！　みじめになるだけだと…": "It only makes me more pathetic...! More miserable...",
"わからないか！！　ウィン！！！": "Can't you see!? Win!!",
"…違う　俺はこんなこと望んじゃいない…": "...No, this isn't what I want...",
"ウィン、俺はこんなことをしたくはない…": "Win, I don't want to do this...",
"術が…　解けだしたのか…！？": "The spell... is it starting to break...!?",
"…う、ううう……っ！！": "...Ngh... hnnn...!!",
"…う、うおおおおおお…！！": "...U-Ughhhh...!!",
"なにやらピピンが苦しみだしたぞ…！？": "Something's making Pipin writhe in pain...!?",
"………ピピン！": ".........Pipin!",
"俺は死を…選ぶ…！！": "I choose... death...!!",
"クソッ　俺としたことが…": "Damn it, to think I'd come to this...",
"なに！？": "What!?",
"ああ…ピピン…！　やめろ！！": "Ah... Pipin...! Stop!!",
"こんな術なんかに…！": "Don't yield to this spell...!",
"ピピン！　正気に戻ったか！？": "Pipin! Are you back in your right mind!?",
"クッ…！　こんな醜態を晒すくらいなら…": "Hmph...! Rather than show such a disgrace...",
"ぐああ…！！": "Gwaah...!!",
"…ううっ…！！": "...Ugh...!!",
"自分の身体を切り刻むことで…": "By cutting his own body...",
"術を…　術に操られた自分を封じようと": "he's trying to seal away the self controlled",
"しているのか…！": "by the spell...!",
"操りの術は解けていない…": "The control spell hasn't lifted...",
"それなのに…　自らの精神力で…": "And yet... with sheer willpower...",
"術と戦っているのか…　ピピン…！": "he's fighting the spell... Pipin...!",
"…はぁ　…はぁ": "...Hah... hah",
"ピピン…　なんという高潔な男…！！": "Pipin... what a noble man...!!",
"ピピンやめろ！　もういい！！": "Pipin, stop! Enough!!",
"お前の身体は　もう十分に傷付いている！！": "Your body is already wounded enough!!",
"それ以上の自傷は必要ない！！": "No more self-harm!!",
"……うるさいッ！！": ".........Shut up!!",
"ピピン！　死んでしまうぞ…　ピピン！": "Pipin! You'll die... Pipin!",
"そろそろ…　お前らでも…": "By now... even you lot...",
"俺にトドメを刺せるだろう…": "should be able to finish me off...",
"気持ちわりいっ！！　なんだよこれ……っ！？": "Gross!! What IS this...!?",
"にしたってデカ過ぎんだろー！！！！": "But even so, this thing's way too big!!!!",
"しっかしなんちゅーバケモンだよ…": "Man, what a monster...",
"闇のエレメントが復活すると、こんなのが": "If the Dark Element revives, this world",
"ウヨウヨする世界になっちまうのかーー！？": "would be swarming with things like this—!?",
"そんな世の中になったら、とてもじゃないけど、": "If the world became like that, no matter how many",
"あたしたちが何人いても追いつかないだろうな": "of us there were, we couldn't keep up.",
"まさに異形のモノって感じだ…！": "It truly feels like something from beyond...!",
"うおおおおおお！": "Whoooaa!",
"禍々しい殺気を周囲にばらまいてやがる…": "It's radiating a sinister bloodlust...",
"でけえぜーーーー！！": "It's huge—!!",
"でもこんなのが相手でも負ける気がしねえ…　": "But even against this, I don't feel like losing...",
"あたしらも紋章の力ですっかり異形のものに": "With the crest's power, I feel like we've",
"なっちまった気がするな…": "become just as monstrous ourselves...",
"さあああああ継承者たちよおおおおおお！！！": "Come, inheritors—!!!",
"私が長年…　研究！　開発！　発見！！": "The many great magics I've researched! Developed!",
"…してきた数々の大魔法を………": "and discovered over the years......",
"惜しみなくすべて披露してやろう！！！！！": "I shall display them all without restraint!!!!!",
"四天王最強の…　大魔道士…　だったよな？": "The strongest of the Four Generals... the Grand Mage... right?",
"ってことは当然、めちゃ強い魔法を使ってくる": "Which means, of course, he uses insanely powerful",
"闇の力や魔法に耐性のあるあたし達でも、": "Even with our resistance to Dark power and magic,",
"どのくらい耐えられるのか…　わからない。": "I don't know how long we can withstand it.",
"これが四天王最強の魔法か…": "So this is the strongest of the Generals' magic...",
"なんつーか…　これといって対策がねえ！！！": "Honestly... we've got no counter for it!!!",
"だーかーらー言ってるだろう！！？？": "That's what I keep telling you!!??",
"私は本来ラスボスポジション！！": "I'm supposed to be the final boss!!",
"あー　気持ちいいいいいいいいいいいい！！！": "Ahh, it feels soooo good!!!",
"お手軽な攻略などなあああああああいいい！！": "There'll be no cheap tricks—!!",
"真っ向勝負のガチバトルでしか私には勝てん！！": "You can only beat me in a straight-up, all-out fight!!",
"ちょっといままで見てきた魔法とは違う…": "This magic's different from what we've seen...",
"きっと、まだ他の魔法も残しているだろうな…": "He's surely holding back other spells...",
"もちのローーーーーーーーーーーーン！！！！": "Of course~!!!!",
"闇いんふるなんとかが広がって…": "The Dark Flu-whatever spreads...",
"みんなが死んでしまう…！！": "and everyone dies...!!",
"闇インフルエンザについては…": "About the Dark Flu...",
"正直スマンかったと思ってる。": "Honestly, I feel bad about that one.",
"は…？": "Huh...?",
"へっ…　結構戦える気がしてきたぜ…": "Heh... I'm starting to feel like we can win...",
"気に入らないものは全てを皆殺しにする…": "Slaughtering everything we dislike...",
"それは、私たちが人間たちからされてきたこと": "that is exactly what was done to us",
"とまったく同じだ…": "by humans...",
"だが…　もうここが限界…　ここが最後…！！": "But... this is our limit... our last stand...!!",
"ここで大きな力を取り戻さねば…": "If we don't reclaim great power here...",
"我々が皆殺しにされてしまう…！！": "we'll be the ones slaughtered...!!",
"なんとかなるかもな！": "We might just make it!",
"何を言ってんだ…　こいつは…": "What is he talking about...",
"最後にキミたちのような楽しい人間に会えて…": "At the end, to meet such delightful humans as you...",
"うれしかったよおおおおおおおおおおお！！！": "it made me so happy—!!!",
"ダメだ！　時間がかかり過ぎている…！": "No good! This is taking too long...!",
"こうしている間にも…魔王とやらが誕生して…": "Even as we speak... the Demon King is being born...",
"なんもいえねええええええ！！！！！": "I've got nothing to say—!!!!!",
"え…、いや、言いまくってるだろう……？": "Eh... no, you're saying plenty......?",
"さすがにホノオも突っ込んだ…！！": "Even Hono had to point that out...!!",
"全能感…ッ！！": "Omnipotence...!!",
"己の持つすべての力…感情を…！！！": "All the power... all the emotion within...!!!",
"ありのまま垂れ流しに解き放つ解放感ッ！！": "The sheer liberation of unleashing it all as it is!!",
"きもちいいいいいいいいいいいい！！！！": "It feels soooo good!!!!",
"やるじゃん　キミたちーーーーーーー！！！！": "Not bad, you lot—!!!!",
"私もちゃんと全ての力を使い切れるように…": "So that I too can use up all my power...",
"頑張るよおおおおおおおお…ッ！！": "I'll do my best—!!",
"かきゅごしりょよおおおおお！！！？？": "Huh-wha-wha—!!!???",
"あー　これちょっとやばい…": "Ah, this is getting a bit dangerous...",
"くっ！！　すげえ気合だ！！": "Ugh!! The spirit behind this is insane!!",
"噛みまくってんのに一切後悔していない！！": "He's stuttering up a storm and feels no shame!!",
"えーいまちょうどですねー": "Um, right about now~",
"私のＨＰが半分になりました！！！！！！！": "my HP has reached half!!!!!!!",
"えー！！？？　なんだそれ、親切だな！！！？": "Huh!!?? What is that, how thoughtful!!!?",
"私にもっとエレメントパワーを………": "Give me more Elemental Power......",
"もっと力おおおおおおおおおおおッ！！！！！": "MORE POWER—!!!!!",
"あっ　走馬灯………　お花畑見えてきた…": "Oh... my life flashing before my eyes...... I can see the flower fields...",
"大魔道士ピケピケの魔力が暴走した！！": "Grand Mage Pikepike's magic runs wild!!",
"ピケピケから猛烈な闇の波動を感じる！！": "A violent wave of Dark energy emanates from Pikepike!!",
"うおっ！？　マジかこいつ…！！": "Whoa!? Is he serious...!!",
"おい…大丈夫か！？": "Hey... are you okay!?",
"敵を心配なくていいんだよ！！": "You don't need to worry about the enemy!!",
"…へえ。": "...Oh.",
"…ほとんど魔法での攻撃なしの殴り合いなら、": "...If it's a brawl with barely any magic,",
"テッペキを二回使えば有利に戦えるはず。": "using Iron Wall twice should give us the edge.",
"自分自身を強化する魔法を持っているのが、": "If you thought only you had magic that",
"あなただけだと思ったら間違いよ？": "strengthens yourself, you're mistaken.",
"そんなスキをあたしは晒さない！": "I won't expose such an opening!",
"氷の魔法はあたしに利かない！": "Ice magic doesn't work on me!",
"無駄なことはやめるんだ！": "Cease your pointless efforts!",
"どうかしら？": "Is that so?",
"一瞬のスキを突いて、至近距離から放てば、": "If I seize a moment's opening and unleash it at",
"あなたでも無効化できないと思うけど…。": "point-blank range, even you can't nullify it...",
"あなたたちのご先祖様じゃないの？": "Wouldn't it be your ancestors?",
"…知らない！": "...I don't know!",
"あなたのつばめ返しって剣術…すごいわね。": "That Swallow Reversal of yours... it's impressive.",
"まるでサムライの使う剣術だわ。": "Just like the swordsmanship of the samurai.",
"…サムライ？　なんだそれは？": "...Samurai? What's that?",
"そういうひとたちがいたのよ…": "There used to be people like that...",
"自信があるのは結構だけれど、": "Confidence is all well and good, but",
"その余裕が、突然あなたの足をすくうのよ。": "that composure will suddenly trip you up.",
"ご忠告感謝するよ、ミケーネ！！": "Thanks for the advice, Mycenae!!",
"油断しないことね…": "Don't let your guard down...",
"あたしは絶対に勝つ気でいるわよ。": "I intend to win, no matter what.",
"大したもんだ…": "Impressive...",
"あたしの剣をこんなに受けて立っている相手は": "You're the first to stand against my blade",
"あんたで初めてだよ。": "this well.",
"うっ…　あと少し…　あと少しで…！！": "Ugh... just a bit more... a bit more...!!",
"ああ、あと少しだ…　": "Ah, just a little more...",
"あと少しで…　あたしの勝ちだあああああ！！": "Just a little more... and I win—!!",
"オレの方はバンバン使ってくからよー！！": "I'll be blasting mine all over the place!!",
"アンタって前のバトルまではよー…": "Until the last battle, you...",
"魔法とか、全然使わなかったよなー？": "never used any magic at all, right?",
"本当は使えたりするんだろー？": "You actually can use it, can't you?",
"いいんだぜ、使ってくれて。": "It's fine, use it.",
"それともオレが強くなり過ぎて…": "Or have I grown so strong that...",
"本気のアンタの圧倒的パワーすら": "even your overwhelming full-power might",
"怖くなくなっちまったってことかー？": "no longer frightens me?",
"…なんだよ？": "...What is it?",
"確かにデカくなって…": "Sure, you've grown bigger...",
"パワーは増してるみてーだけどよー": "and your power seems greater, but—",
"変わり映えしねーぜ？": "it's nothing new, is it?",
"本当にこんなモンか、ナウー！？": "Is this really all you've got, Nau!?",
"どっちなんだよ、本当は魔法があるのかよ！！": "Which is it—do you have magic or not!!",
"少しは喋ってくれーーーーー！！": "Say something, will you!!",
"だーかーらー…": "That's... why...",
"前と同じパターンの攻撃ばっかじゃ、": "If you keep using the same attack patterns,",
"いくらパワーがあっても通用しねーぜ！！": "all that power won't do you any good!!",
"う…お………　　なんだって…？": "Ugh... wh-what...?",
"…光の柱に　魔力を注ぎ込んだ　我らには…": "...We who poured our magic into the Pillar of Light...",
"…これで　本気なのだ　ホノオ…": "...with this, we are serious, Hono...",
"こんなモンか…　ナウー…": "Is this all... Nau...",
"…くっ！　そうかよ…": "...Hmph! Fine then...",
"それならそれでしかたねえ…": "If that's how it is, so be it...",
"でもこっちは本気で行かせてもらうぜ…": "But I'll be going all out too...",
"急いでるんだ…　使命があるんだオレには！！": "I'm in a hurry... I have a mission!!",
"………コクリ": ".........(nod)",
"アンタの力が、こんなモンなワケがねえだろ！": "There's no way that's all your power!",
"…我は本気だ　ホノオよ": "...I am serious, Hono.",
"…今のは効いたはず…！！": "...That should have landed...!!",
"…なんだあ？　　へへ…　とにかく…": "...What the—? Heh... anyway...",
"やっと新しい技を見せてくれるみてえだなー": "Looks like he's finally showing a new move~",
"…だが、アンタはもう瀕死のはずだ…": "...But you should be at death's door...",
"こっちの攻撃の手は緩めねえぜーーー！！！！": "We won't be letting up—!!!!",
"すぐに死なれちゃったらつまんないからさあ？": "It wouldn't be fun if you died right away, so~?",
"さあて…　魔王になったボクの力が、": "Now then... just how incredible the power of me,",
"いったいどれだけ凄いのかを…": "the Demon King, is...",
"試させてもらうねー？": "let me test it out on you~?",
"本気で耐えてねー": "Hold out for real, okay?",
"…んだよ　死ねよ！！！！！！": "...Damn it, just die!!!!!!",
"魔王のボクが攻撃してるんだぞーーー！！！？": "The Demon King me is attacking—!!!?",
"アレー？": "Hmm?",
"意外と耐えちゃったねえ…　1ターン！！": "You actually survived... one turn!!",
"やるじゃーーーーん！！": "Not bad~!!",
"意外と楽しませてくれるんだねー！？": "You're more entertaining than I thought!?",
"奴の炎の魔法は俺の魔法で相殺できる。": "His fire magic can be canceled by my magic.",
"しかし魔王とか名乗るくらいだ…": "But he calls himself a Demon King...",
"他にも危険な技があるかも知れん。": "he may have other dangerous tricks.",
"気を引き締めつつも、チャンスと見れば": "Stay sharp, and when we see an opening,",
"一気に攻めるぞ！！": "we strike all at once!!",
"赤いのがジャマだ…": "The red one is in the way...",
"赤いのがジャマなんだよーー！！！！": "The red one's in the way—!!!!",
"おいおい…": "Hey now...",
"魔王ってのはこんなモンなのか？": "Is this all a Demon King amounts to?",
"派手なナリをしているだけのことはあるか。": "At least the flashy getup's got some bite.",
"くっそおおおおおおおおおおお！！！！！！": "Dammit—!!!!!!",
"ボクは魔王なんだ…": "I am the Demon King...",
"こんなところで終わってたまるかー！！！！": "I won't end here—!!!!",
"意外とタフだな。": "He's tougher than expected.",
"もっとパワーを…": "More power...",
"闇のエレメントパワーをおおおおお！！！！": "DARK ELEMENTAL POWER—!!!!",
"時間をかけると、奴がパワーアップしてしまう": "If we take too long, he'll power up",
"かも知れん…": "even further...",
"闇のエレメントパワー自体と同化すると…": "Once you merge with the Dark Elemental Power itself...",
"自我を保てるかどうかわからないって…": "you can't be sure you'll keep your sense of self...",
"だからこそ、四天王の中で最も強いピケピケが": "That's why Pikepike, the strongest of the Generals,",
"魔王になるはずだった…": "was supposed to become the Demon King...",
"フン、分からんでもない…": "Hmph, I can see the sense in it...",
"お前のようなガキに、自我を保つことが": "A brat like you keeping your sense of self—",
"もう…　ダメだ…　終わりだ…": "It's... over... this is the end...",
"できるとは思えないからな。": "I can't see that happening.",
"ボクは嫌だった…": "I didn't want it...",
"どんなに強大な力を得られるとしても、": "No matter how vast the power,",
"自分がいなくなってしまうなんて…": "losing myself was just...",
"だけど…　もう終わりだ…": "But... it's over now...",
"こんなダサいやられ方するくらいなら…": "If I'm to be taken down this lamely...",
"もうどうなってもいい…": "I don't care what happens anymore...",
"オマエらだけは絶対にぶっ殺す…！！！！": "But you lot—I'll kill you all for sure...!!!!",
"まずい！！　ウィン離れろ！！": "Danger!! Win, get away!!",
"なんだ、降参か？": "What, surrendering?",
"悪いが、受け入れられないぞ。": "Sorry, but I won't accept that.",
"ピケピケが言っていた…": "Pikepike said...",
"う…ぐぐぐがガガガァァ……！！": "Ugh... grrrgh...!!",
"オマエらも一緒に飲み込まれろォォォ…ッ！！": "You lot get swallowed up too—!!",
"ウィン！　立て直すぞ！！": "Win! Let's regroup!!",
"魔法、アイテム…使い尽くすつもりで行け！": "Use up every spell and item you have!",
"グググダダダハハハハーーッ……！！！": "Grrrrgahahaha—......!!!",
"流れ込んでくるゾオオオオオゥゥゥゥ……": "It's flooding in—......",
"とてつもないパワーガアアァァァ……": "An incredible power—......",
"飲み込まれる…飲み込まれてしまう……": "Swallowed up... I'm being swallowed up......",
"いイイイィィやぁぁぁだあああぁーーッ！！！": "N-NOooo—!!!",
"ダフィール！！　": "Dafill!!",
"まだ俺の声が聞こえているなら…": "If you can still hear my voice...",
"老いぼれや無能の先輩がたなど無視して…": "ignore those old and useless predecessors...",
"俺たちとのバトルに集中しろ…！！": "and focus on our battle...!!",
"ウウゥゥ…グガガアァァァーー…ッ！！！！": "Uugh... grrraaah—!!!!",
"…な…にぃ…？": "...Wh-What...?",
"赤い…の………？": "The... red one......?",
"何よりも自分を失いたくないと思う気持ち…": "That wish to never lose yourself above all...",
"それは、お前の誇りだ…プライドだ。": "that is your pride.",
"…誇り…　ボクの…？": "...Pride... Mine...?",
"…それは誰にも消せん！！": "...No one can erase that!!",
"自分ですら持て余しているくせに…": "You can't even handle yourself...",
"これだけ極限の状況ですら…": "and in this extreme situation, even now...",
"仲間の思いよりも、自分の都合を捨てられん…": "you can't set aside your own convenience for your comrades' sake...",
"何て自己中、ナルシストだ…": "What a selfish narcissist...",
"お…オマエに言われたくねーーーーーーー！！": "Y-You're one to talk—!!",
"なら腹をくくれと言ってるんだ…。": "Then I'm telling you to steel yourself...",
"くくれず、外野を無視できないままなら、": "If you can't, and can't ignore the sidelines,",
"結局お前はその程度だということだ！！": "then that's all you amount to!!",
"このまま全て闇のエレメントに飲み込まれ…": "To be swallowed by the Dark Element whole...",
"…偉そうに…オマエ……": "...So high and mighty... you...",
"ボクの兄ちゃんみたいなコト言いやがってェ…": "sounding just like my big brother...",
"フン、四天王にも兄弟がいるとはな…。": "Hmph, so even a Four General has a brother...",
"…ボクだって元々はヒトの子だ…": "...I was a human child once, too...",
"好きで四天王になった奴なんて………": "Who'd ever choose to become a Four General......",
"オマエらにも飲み込まれて………": "You'll be swallowed too......",
"いないンだよォォオオーー…ッ！！！！！": "I refuse—!!!!!",
"消えてしまうなんてイヤだ………": "I don't want to vanish......",
"…それでも兄がいたことといい、": "...Yet the fact that you had a brother,",
"その自己中な性格といい…、": "and that selfish personality of yours...",
"それは人間の頃から変わらないんだろうが…？": "those haven't changed since you were human, have they...?",
"…なら、お前にも他の四天王と同じように…": "...Then like the other Generals, you too...",
"お前なりの歴史や感情があるってことだ…": "have your own history and feelings...",
"なのになぜ、まだ他の四天王に気兼ねする？": "So why are you still deferring to the other Generals?",
"お前にも兄がいたらしい…": "You apparently had a brother...",
"お前だけの都合で、好きなケジメの付け方して": "You can end things however you please—",
"いいだろうが…！！": "that's your right...!!",
"……ッ": "......Hmph",
"しかも以前は人間だったとはな…": "And to think you were once human...",
"…もう殆ど覚えちゃいない………ッ！！": "...I barely remember any of it......!!",
"強い闇のエレメントパワー自体が元々人間を": "The very nature of raw Dark Elemental Power is",
"蝕むものだからなァァーーーッ！！！！": "to corrode humans from the start—!!!!",
"出来るのか…！？": "Can he do it...!?",
"うう…おおオオオォォー…！！！！": "Ugh... oooooh...!!!!",
"流れ込んでくる…！！": "It's flooding in...!!",
"この力はァァァ…　ミケェェネかあァァ…！！": "This power... it's Mycenae's...!!",
"…こいつ、他の四天王の力を吸収することも": "...This one can absorb the other Generals'",
"感情…なのかァァァ……": "power—and their emotions too...",
"入って来るなァーーーーーッ…！！！！": "Stay out—!!!!",
"…フン、どうやら四天王の力だけでなく、": "...Hmph, it seems he absorbs not just the power,",
"その人格も吸収してしまうようだな…": "but the personalities of the Generals too...",
"そんな連中の人格までをも吸収してしまって、": "Having absorbed even their personas, can a brat",
"果たしてキサマのようなガキンチョが自分を": "like you possibly keep yourself intact...?",
"保てるか…　見ものだな、ダフィール…！！": "This will be worth watching, Dafill...!!",
"グググゥゥ………オオアアァァ…ッ！！！": "Grrrgh... ooaaah...!!!",
"やめろ！！　入って来るなァッ…！！": "Stop!! Stay out—!!",
"ミィィケェェネェー………": "Myyceeenaee......",
"これはオマエのキオクなのかぁぁ……": "Are these your memories...?",
"早くも自分を失いかけているようだな…": "He's already starting to lose himself...",
"ダフィール…！！": "Dafill...!!",
"それがキサマの弱さだ…": "That is your weakness...",
"どれだけ強大な力を手にしようと…": "No matter how vast the power you grasp...",
"内に強さを持たないものに、その力は扱えん！！": "power cannot be wielded by one who lacks inner strength!!",
"ミケーネぶりざーどおお…はああああ": "Mycenae Blizzzard... haaaaa",
"ググガガガ…ガガアアァァーッ！！！！": "Grrrgh... rraaah!!!!",
"オマエも黙れえええェェェーーッ…！！！！": "You shut up too—!!!!",
"効かない…効かない…！！！！": "It won't work... it won't work...!!!!",
"そんなコト分かってるよ…！！！！！": "I know that...!!!!!",
"うるさあああああいいイイィィッ！！！！": "Shut UUUUUP!!!!",
"黙れレレエエェェェーーーーッ！！！！！": "SILENCE!!!!!!",
"さらに反撃確率もアップ！！": "His counter rate rises further!!",
"ダフィ－ルの構えにスキがなくなった！！": "Dafill's stance becomes flawless!!",
"力だけェェェ…　力だけ寄こせェェ…！！": "Power only... just give me power...!!",
"オマエらの…こんなフクザツでカイキな……": "Your... convoluted, twisted......",
"ややこしい感情と歴史はいらない…ッ！！": "messy emotions and history—I don't want them!!",
"チカラだけをヨコセェェェー……ッ！！！！": "JUST GIVE ME POWER—......!!!!",
"自分にすべてを託して散っていった仲間の、": "The comrades who gave you everything and fell...",
"その思い…その重さ…　すべて拒否するか…": "their feelings, their weight... you'd reject it all...",
"…ヘドが出るほどのガキンチョだな…。": "...You're a brat sickening enough to make one retch...",
"なんでいまボクは黙ったァァ……！！": "Why did I go quiet just now...!!",
"オマエだな……ヌヌアアアウウゥゥゥー…！！": "It's you—...!!",
"大魔王ダフィールの攻撃力とぼうぎょ力がアップした！！": "Great Demon King Dafill's attack and defense increase!!",
"そして…　めちゃくちゃ難解な感情なんだ…": "And... these feelings are impossibly complex...",
"ダフィールから猛烈な闇の波動を感じる！！": "A violent wave of Dark energy emanates from Dafill!!",
"ダフィールの魔力が暴走した！！": "Dafill's magic runs wild!!",
"グガガダダガハハハァァァー……ッ！！！！": "Grrrrgahahaha—......!!!!",
"ピ…ケ…ピ…ケエエェェーー……ッ！！！！": "Pi... ke... Pi... keeee......!!!!",
"クッ…！！": "Hmph...!!",
"なんだ…気圧される…！！": "What... I'm being overwhelmed...!!",
"ウィン…これがあのピ何とかの力なのか…！？": "Win... so this is that Pi-whatever's power...!?",
"逆らうな…　逆らってはならんンンのだぁ…": "Don't resist... you must not resist......",
"闇の力の奔流からからァァ……！！！！": "from the surging torrent of Dark power......!!!!",
"闇のエレメントに完全に身を任せねバァァ…": "Only by surrendering wholly to the Dark Element......",
"真の大魔王に…は…ワワァァ……ァ………": "can one... become the true Great Demon King......",
"ウウうおおおああああぁぁーー……ッ！！！！": "Uuughaaaaah—......!!!!",
"ボクはダフィールだァァァァ……！！！！": "I am Dafill—......!!!!",
"どうもこの辺りからが本番らしい…": "It seems the real fight starts around here...",
"ウィン、死ぬなよ！！": "Win, don't die!!",
"コノ…チカラは………ッ！！": "This... power......!!",
"うう…グフ…ガ…ァァ…ああああああ！！！": "Ugh... grh... gaah... aaaah!!!",
"なんて凄まじい魔力…　膨大な知識…": "What immense magic... vast knowledge...",
"いまの奴にはスキが殆どないから、": "He has almost no openings right now, so",
"大ダメージを与えるのが難しい…": "dealing heavy damage will be hard...",
"そこで奴にスキを作る作戦だ。": "So here's the plan to create an opening.",
"お前のカマイタチで奴の足を攻撃した瞬間に、": "The moment your Kamaitachi strikes his feet,",
"ググルルううおおおあああぁぁぁぁ……！！": "Grrrluuughaaah......!!",
"俺がフェイント攻撃をしかける…。": "I'll follow with a Feint Thrust...",
"うまくいけば、奴のぼうぎょと素早さを同時に": "If it works, we can lower his defense and agility",
"ダウンさせることができるだろう…どうだ？": "at the same time... what do you think?",
"負けねえゾ……　ゼッテーェェ……": "I won't lose...... not a chance......",
"ウィンとピピンはカマカゼを編み出した！": "Win and Pipin create Kamakaze!",
"負けねえぞおおおおおおおまえらあああ！！！！": "I won't lose to you—!!!!",
"…ウィン、俺にちょっとした考えがある。": "...Win, I've got an idea.",
"お前の魔法と俺のスキルを組み合わせた攻撃だ": "A combined attack of your magic and my skill.",
"普通にやったんじゃうまくいかない。": "It won't work if we do it normally.",
"俺が丸焦げになるか、よくても雷の力が": "I'd end up charred, or at best the lightning",
"地面に逃げてしまうからな…。": "would escape into the ground...",
"そこでだ…　俺のスキル、浮雲渡りだ。": "So... I use my skill, Walking on Clouds.",
"己をぉぉ…滅っせぇぇェェ…": "Destroy yourself......",
"俺が宙に浮いている間に、オマエが俺の剣に": "While I'm airborne, you drop your Thunderclap",
"イカヅチを落とす…": "onto my sword...",
"そして着地するまでの間に俺が攻撃すれば…": "Then if I attack before I land...",
"全ての雷のパワーがアイツに伝わる。": "all the lightning's power transfers to him.",
"想像もつかん威力になるだろう…": "The force would be unimaginable...",
"どちらかがタイミングをミスれば、": "If either of us mistimes it,",
"さもなくばァ…　敗れゥゥ……ううああ！！": "or else... we lose...... ugh!!",
"俺は丸焦げになるが…、どうだ、やれるか？": "I'd be roasted, but... can you do it?",
"ウィンとピピンはイヅナを編み出した！！": "Win and Pipin create Izuna!!",
"黙れェェナウゥゥーーッ…！！！！": "Silence, Nau—!!!!",
"ウィン…お前のイカヅチを俺の剣に落とす技を": "Win... I've been thinking of a move where you",
"考えていたんだが…": "drop your Thunderclap on my sword...",
"己が無くなるのォォーーーッ！！": "My very self vanishing—!!",
"己が無視されるのォォォーーーッ！！！": "Being utterly ignored—!!!",
"ググガガうぅおぉあぁーーー……ッ！！！！": "Grrrgh—......!!!!",
"ウィン、気付いているか？": "Win, have you noticed?",
"アイツはもう、俺たちを見ていない…": "He's not even looking at us anymore...",
"見えていない…！！": "He can't see us...!!",
"恐れるかァァ…怯えるかァァ……！！！！": "Does it fear...? Does it tremble......!!!!",
"いまなら…": "Now is our chance...",
"俺の魔法を相殺されずに発動できるだろう…": "I can cast my magic without it being canceled...",
"そこでだ…": "So here's the plan...",
"不意を突いて俺がアイツを水浸しにする…": "I'll catch him off guard and soak him with water...",
"そこにお前のイカヅチを落とせ。": "Then you drop your Thunderclap on him.",
"真実がァァ…歴史がァァ…": "The truth... history......",
"辺り一面水浸しだ、逃れる術はない…。": "Everything's drenched—there's no escape...",
"しかも雷のパワーは地面に分散せず、": "And the lightning won't disperse into the ground,",
"びしょ濡れの奴に集中するってわけだ。": "it'll concentrate on the soaking-wet target.",
"ウィンとピピンはミカヅチを編み出した！！": "Win and Pipin create Mikazuchi!!",
"失われることよりもォォォ………ッ！！！": "More than what would be lost......!!!",
"卑小で卑俗でか弱い己れの消失ォォォ………": "The vanishing of this petty, vulgar, fragile self......",
"闇の復活もォォォ………！！！": "The Dark's revival......!!!",
"闇の勝利もォォォ………！！！！！": "The Dark's victory......!!!!!",
"ボクにはどうでもいいィィィー……ッ！！！！": "I don't care about any of it......!!!!",
"フン…　アイツ、仲間のことばに全く従う気が": "Hmph... he's got no intention of listening",
"ないみたいだな…。": "to his allies...",
"真の意味での闇との一体化…大魔王化には…": "True fusion with the Dark... to become the Great Demon King...",
"黙れッェェ…　ピケピケェェ…！！": "Silence... Pikepike...!!",
"アイツの自我がジャマなようだ。": "His sense of self seems to be in the way.",
"…ちょびっとだけ、哀れだな、アイツ。": "...I feel just a tiny bit sorry for him.",
"ナウーゥゥゥ…　ミケェェネェーッ…！！！！": "Nauu... Myceenaee...!!!!",
"ボクは消えないッ！！！！": "I won't disappear!!!!",
"ボクはまだ何も成していない…ッ！！！！": "I haven't accomplished anything yet...!!!!",
"絶対に勝てねえ！！": "There's no way we can win!!",
"卑怯かも知れねえが…": "It might be underhanded, but...",
"一回勝たせてもらうぜ！！": "let me take this one!!",
"……………（ゆっくり頷いてから武器を構える": ".........(It slowly nods, then raises its weapon)",
"くそ…二人で勝ったんじゃ、試練を果たした": "Damn... winning with two of us won't count as",
"ことにならなそうだなあ…": "clearing the trial...",
"………（困": ".........(awkward)",
"とはいえ、オレはコイツにひとりじゃ": "Still, I can't beat this guy",
"なんか左手の紋章が光りまくってる…": "My left-hand crest is blazing away...",
"いかにも魔法とか使えそうな感じだぜ！": "It really looks like it could cast magic!",
"ウィンの紋章もみどり色に輝いている！": "Win's crest glows green as well!",
"ウィンはホノオに名前を教えた": "Win tells Hono his name.",
"オーケー！　ウィンて言うんだな！": "Okay! So you're Win!",
"オレはホノオだぜ！　よろしくな！": "I'm Hono! Nice to meet you!",
"この鎧のオッサンは意外とすばやいうえに…": "This armored geezer's surprisingly fast, and...",
"ウィンのそのハヤテの魔法を使えば、": "with your Hayate spell,",
"アイツよりも先に動ける…": "we can act before him...",
"つまり…　コレは勝てるぜーーー！！": "Which means... we can win—!!",
"こっちを気絶させたり、転ばせてくるから、": "He stuns us and knocks us down, so",
"ちっともこっちの番にならねーんだ…": "our turns never come...",
"だけどオマエの…　オマエ…": "But your... you...",
"おっ？　もしかして…　いけるか！？": "Oh? Could it be... we can do this!?",
"どうもいままでの魔物とは様子が違う…": "This one feels different from the monsters so far...",
"ウィン、気を引き締めろよ！": "Win, stay sharp!",
"最大出力のブリザード…　解禁するわ！！": "Maximum-output Blizzard... I'm unleashing it!!",
"なんか奥の手がありやがるのか…？": "So she's got an ace up her sleeve...?",
"………っ！！！！": ".........!!!!",
"…効いてる！！": "...It's working!!",
"このまま一気にたたみかけろ！！": "Press the attack all at once!!",
"もう四の五の言ってられないわね…": "No time to dither...",
"…手を抜いている？　マジか…": "...Holding back? Seriously...",
"ホノオ！集中しろ！": "Hono! Focus!",
"ナウー…　この子たち、強いわ。": "Nau... these kids are strong.",
"あたしたちの予想を超える力を持っている…": "They hold power beyond our expectations...",
"いつもみたいに手を抜かなくてもいいはずよ。": "You don't need to hold back like usual.",
"二対二なんだし、条件もフェアでしょう？": "It's two on two, so the terms are fair, right?",
"ま、待て！！": "W-Wait!!",
"まだこれからってときに…逃げんじゃねー！！": "Don't run at a time like this!!",
"ホノオ！": "Hono!",
"喋ってるヒマがあるなら攻撃するんだ！！": "If you've got time to talk, attack!!",
"ナウー…　やっぱり…": "Nau... just as I thought...",
"思わせぶりな会話をして…": "talking all cryptic...",
"消えて脱出するスキを作ろうとしているんだ…": "he's trying to make an opening to vanish and escape...",
"乗せられるなよ！": "Don't fall for it!",
"ふーん　相変わらず口の達者な子…": "Hmm, as silver-tongued as ever...",
"いいわ、もう少しだけ相手してあげる。": "Fine, I'll play along a little longer.",
"だけど…": "But...",
"あなた、一対一の決闘にしか興味ないのね…": "you're only interested in one-on-one duels...",
"ナウーが全然やる気ないのよ。": "Nau has no interest at all.",
"彼を本気にさせるくらいに…": "Try to work a little harder...",
"あなたたちももっと頑張りなさい！？": "to make him serious!?",
"時間がかかり過ぎたわ。": "This has taken too long.",
"これ以上はただの消耗戦…": "Any more would be a mere war of attrition...",
"帰るわよ、ナウー！": "We're leaving, Nau!",
"ちょっとだけ遊ばせてもらうよーー？": "Let me have a bit of fun first~?",
"キミたちにはボクの炎を防ぐ手段が": "You lot have no way to block my flames,",
"ないから…": "so...",
"よく燃えるだろうなーーーー！！？？": "you'll burn nicely, won't you—!!??",
"奴は自分でも散々言っているが…": "He keeps saying it himself, but...",
"火を使うらしい。": "it seems he uses fire.",
"ホントはーーー　自分で戦うつもりなんて": "The truth is—I never planned to fight",
"これといって対策も思いつかんが…": "We can't think of any real counter...",
"とりあえず早めに回復をしながら戦うぞ…。": "For now, we fight while healing early...",
"ウィンは頷いた！": "Win nodded!",
"なかったんだケドーーー": "there wasn't any, but—",
"来たのが風の紋章の継承者とーーー": "the ones who came were the Wind Crest inheritor and—",
"よくわかんない赤いヒトだけだったんでーー": "some weird red person, so—",
"フン…さあな。": "Hmph... who knows.",
"お前の力が自分で思っているよりも、": "Your power just isn't as impressive",
"意外と大したことないんだろう。": "as you think it is.",
"いやいやいやいやー": "No no no no~",
"金髪の子は明らかにヤケドだらけだよー？": "The blond one's clearly covered in burns~?",
"………おかしいなーーー": ".........How strange~",
"なんでーーー？": "Why~?",
"赤い服着てるからとか言うなよー？": "Don't you dare say it's because of the red clothes~?",
"面白くないからーーー": "that's not funny—",
"…本当にそうなのか…？": "...Is that really so...?",
"ウィン、お前から見ても…？": "Win, from where you stand...?",
"まあ…、なんでもいいさ。": "Well... whatever.",
"これで、お前に勝つ見込みもあると分かった…": "At least I know I have a chance against you now...",
"そろそろ本気でいかせてもらう…！": "Time for me to get serious...!",
"こわーーーーー！！！！！": "Scary—!!!!!",
"怖過ぎてムリーーーー！！！！": "Too scary, can't do it!!!!",
"怖過ぎるのであと5ターンで終りにしまーす": "It's so scary, I'll end this in five more turns~",
"5ターン以内にボクを倒せるようにー…": "Try to beat me within five turns~...",
"せいぜいがんばってくださーーーい！！！？": "Do your very best—!!!?",
"ふざけやがって…！！": "You've got some nerve...!!",
"おい、赤いのさーーー": "Hey, red one~",
"オマエ、継承者でもないのに…": "You're not even an inheritor, yet...",
"ボクの炎にちょっと耐性あるよねーーー？": "you've got a bit of resistance to my flames, don't you~?",
"ざんねんでしたーーーー！！！！": "Too bad for you—!!!!",
"ここまででーーす　ガチバトルごっこ終わり！！": "That's it—the real-battle game is over!!",
"ちなみにピピンが剣ではなく、杖を持って": "By the way, Pipin appears to be holding a staff",
"いるように見えるのだが…　これは…？": "rather than a sword... what is this...?",
"おそらくダフィールの魔力で見た目が変わって": "His weapon's appearance is likely altered by",
"いるのでしょう…　恐ろしい力だ…": "Dafill's magic... a fearsome power...",
"しかしあれは剣なのです、サクソン殿！！": "But that IS a sword, Lord Saxon!!",
"俺を憐れむというのか…ウィン……！！": "You would pity me... Win......!!",
"あれは一体なんだ…　どういう構造なんだ…": "What on earth is that... how is it built...",
"なんにしてもパッと見で強そうだ…": "Either way, it looks strong at a glance...",
"サポート系の魔法をしっかり使った方がいいな": "Better to use support magic properly.",
"何となくカメのようにも見えるが…": "It sort of looks like a turtle, but...",
"そんであの甲羅から凄い勢いで出してる煙…？": "And that smoke pouring from its shell...?",
"近くで見ると、完全に…　イヌ…か？": "Up close... it's completely... a dog...?",
"イヌ？はイヌ？でも、普通のイヌとは違う…": "A dog? It's a dog? But not like any ordinary dog...",
"くっ…！！　気圧されるな！！": "Ugh...!! Don't be cowed!!",
"いまのあたしたちなら、やれるはずだ！！": "With us as we are now, we can do this!!",
"拍子抜けだな…": "What a letdown...",
"ウィン、さっさと決めてしまおう。": "Win, let's end this quickly.",
"ウィン、急ぐぞ！": "Win, we hurry!",
"ムダなまでにデカい、オマエのその誇り…": "Your pride, absurdly swollen...",
"だからこれはもうお前の戦いだ…": "so this is now your battle...",
"まるで、俺みたいだぜ…！！": "Just like me...!!",
"うげえええ！！！！　きもち悪すぎるーー！！": "Ew—!!!! Too gross—!!",
"な…　なんだこれは…！？": "Wh-...What is this...!?",
"どこだよここ！！？？": "Where is this!!??",
"なんだーーー！！！？？": "What the—!!!??",
"あのデッカイきもちわりいのはよーー！！？？": "That huge gross thing—!!??",
"もうやだああああああああああ！！！！": "I can't take it—!!!!",
"帰りたいーーーーーーーー！！！！！": "I want to go home—!!!!!",
"こいつ…不死身なのか…？": "Is this thing... immortal...?",
"いくら攻撃しても、ちっとも手応えがない…！": "No matter how much we hit it, there's no feedback...!",
"ちくしょーーー！！！": "Damn it—!!!",
"なんでこんな目に合わなきゃいけねえんだ！！": "Why do we have to suffer this!!",
"「いままで散々痛い目に合わせてくれた…": '"You\'ve put me through so much pain...',
"　お礼をたっぷりとさせてもらうぜ！！": " now let me repay you in full!!",
"「…くっ": '"...Hmph',
"　言ってることよく分からないが…": " I can't quite follow what you're saying, but...",
"　確かにコイツ、只者じゃない…！！": " this one's certainly no ordinary foe...!!",
"「しっかしマジで誰なんだよ、こいつ…": '"Seriously though, who is this guy...',
"「俺は何度倒されても　立ち上がった…": '"No matter how many times I was struck down, I rose again...',
"　死んだと思っても　ギリギリ生きていて…": " even when I thought I was dead, I clung to life...",
"「そうして遂に…": '"And so, at last...',
"　俺はこの力を手に入れたんだ…": " I gained this power...",
"　お前らを倒せる力をな！！": " the power to defeat you!!",
"「…ふん": '"...Heh',
"　俺の方が強い。": " I'm stronger.",
"「どうだ！　この素早さ！　戦闘技術！！": '"How do you like it! This speed! This technique!!',
"　まさに伝説級の強さだろう！！": " Truly legendary strength, wouldn\'t you say!!",
"「つええ…": '"He\'s strong...',
"　こんな強い人間に会ったコトがねえ…！！": " I've never met a human this strong...!!",
"「しかし…なんだろう…": '"But... what is it...',
"　コイツの力には　なんか…": " his power has something...",
"　感じるよ、闇の力みたいなの…": " I sense it—something like Dark power...",
"「ああ…　フツーじゃねーよ…": '"Yeah... this ain\'t normal...',
"　気を付けた方がいいと思うぜ": " I'd be careful if I were you.",
"　騎士隊長さん。": " Knight Captain.",
"「クッ…！！": '"Hmph...!!',
"「…俺はもう騎士じゃない": '"...I\'m not a knight anymore.',
"　ダメなのか…　こんなに強くなっても…！！": " Is that not allowed... even now that I'm this strong...!!",
"「所詮は人間…": '"In the end, they\'re human...',
"　化け物みたいな体力ではなさそうだ。": " they won\'t have a monster\'s stamina.",
"「ハァ…　ハァ…": '"Hah... hah...',
"「そろそろ終わりのようだな　盗賊野郎": '"It\'s about time you met your end, you bandit scum.',
"「あんだと…？": '"What was that...?',
"　まだ始まってもねえんだよーーーーー！！！": " This isn\'t even close to over—!!!",
"こんどこそ…！全部会心の一撃が出るかも！！": "This time...! Every hit might be a critical!!",
"ごちゃごちゃ喋ってないで、": "Enough chatter—",
"さっさとこいつをぶちのめすぞ！": "let's beat this guy down!",
"しっかし、こんなバケモノ…": "Still, a monster like this...",
"一体どこから来やがったんだ？": "where on earth did it come from?",
"龍のお社の方から来たって誰かが": "Someone said it came from",
"言ってたよ…": "around the Dragon Shrine...",
"お！　見た事のあるやつだぜ！": "Oh! I know this one!",
"さあ、これで終りにしてあげる！": "Come, let me end this!",
"私たち闇の四天王と…": "The clash between the Four Dark Generals",
"あなたたち継承者との争いを！！": "and you inheritors—let it end here!!",
"くっそーーーーーーー！！": "Damn it—!!",
"まったく勝てる気がしねえぜ、さすがに": "I honestly can't see us winning,",
"今回ばかりはよーーーーーーー！！！": "not this time—!!!",
"闇の四天王のこの私と…": "Me, a Four Dark General, and...",
"すまん、ホノオ、ウィン！": "Sorry, Hono, Win!",
"なんとかあんたたちの力で…": "Somehow, with your power...",
"この場をしのいでくれ……！！": "hold the line here......!!",
"そして闇の結晶最強の…　この青龍！": "And Seiryu, the strongest Dark Crystal...!",
"同時に相手することなんて…": "To face them both at once...",
"もしあなたたち全員が…紋章を持っていた": "Even if all of you carried crests,",
"としても…": "it would be...",
"ほとんど不可能だったでしょうね…": "nearly impossible, wouldn't it...",
"えーと…　ちょっと": "Um... a moment.",
"青龍さん、ちゃんと戦ってもらえるかしら…？": "Seiryu, could you please fight properly...?",
"…　なんだ？": "...What?",
"様子がおかしい…。": "Something's off...",
"みんな、守りを固めて様子を見た方がいい。": "Everyone, better fortify and watch closely.",
"ちょっと…　ちょっとちょっと青龍…！？": "Hey... hey hey, Seiryu...!?",
"ちゃんと言うことを聞いてもらえるかしら…": "Will you please listen to me...",
"私だってあなたの爪でひっかかれたら": "Even I would hurt badly if you",
"すごく痛いんだけど…": "scratched me with those claws...",
"なんだ…あいつら？": "What's going on with them...?",
"もはや明らかに…": "It's now clear...",
"青龍さん真面目にやる気ないわね…コレ…": "Seiryu has no intention of fighting seriously...",
"龍はオレらと戦う気がなさそうだぜ…？": "The dragon doesn't seem to want to fight us...?",
"どういうことだ…。": "What does this mean...",
"はいストップ！ストーー―――ップ！": "Okay, stop! Stooop!",
"タイムです！タイム！！": "Time out! Time out!!",
"青龍さん…ちょっと会議です、会議…。": "Seiryu... we need a meeting, a meeting...",
"オレが成長していないと思うなよ…ナウ―！！": "Don't think I haven't grown... Nau!!",
"遠慮はいらねえ！　本気で来やがれーー！！": "No holding back! Come at me for real—!!",
"ずっとイメージしていたぜ…": "I've been picturing it all along...",
"アンタの攻撃パターンをよーーーー": "your attack patterns—",
"オレはアンタにぜってー勝つ！！": "I'm definitely beating you!!",
"へへ！　いや、わかんねーわ…": "Heh! Nah, I don't know...",
"焦ってるみてーだな、ナウ―！": "You seem tense, Nau!",
"いける…！　集中しろ、オレ…！！": "I can do this...! Focus, me...!!",
"お前がその紋章の力でどこまでやれるのか…": "Let's see how far you can go with the crest's power...",
"ウィン、見せてみろよ。": "Win, show me.",
"ウィンは頷いて、武器を構えた": "Win nods and readies his weapon.",
"なるほどな…　お前の紋章の力も、": "I see... I've got a good handle on your crest's power",
"このバケモノの力も、大体分かった。": "and this monster's strength.",
"ウィン、そのハヤテの魔法を俺にかけろ！": "Win, cast your Hayate on me!",
"俺が常に先手を取ることが出来れば…": "If I can always strike first...",
"この敵は単なるザコだ！": "this foe is mere fodder!",
"フン…　その目、一応分かってるみたいだな。": "Hmph... those eyes show you understand.",
"ウィン、お前もその素早さを活かして、": "Win, use that agility of yours to",
"俺が戦いやすいようにサポートするんだ。": "support me so I can fight easier.",
"お前の紋章はサポート向きだ。": "Your crest suits support.",
"…分かるか？": "...Understand?",
"俺を憐れむのか…ウィン……！！": "You would pity me... Win......!!",
"…っ！！": "...!!",
"あれは一体なんだ…　見たことのない武器だ…": "What on earth is that... a weapon we've never seen...",
"なんにしてもパッと見…　肉弾戦が強そうだ…": "Either way, at a glance... it looks strong in melee...",
"ナガレのテッペキの魔法が活躍しそうだぜー？": "Nagare's Iron Wall spell should shine here~?",
"ところどころ人間のようにも見えるが…": "Parts of it look almost human, but...",
"そんであの腕に繋がった凄い音出してる刃物？": "And that blade attached to its arm, making that awful noise?",
"近くで見ると、完全に龍だなコイツ！": "Up close, it's completely a dragon!",
"龍は龍でも、セイリューのあいつとは違う…": "A dragon, sure, but not like the one in Seiryu...",
"くっ…！！　やれるのか…あたしに…！！": "Ugh...!! Can I do this...!!",
"ちょびっとだけ、拍子抜けだな…": "Just a tiny bit anticlimactic...",
"ウィン、そろそろ急ぐぞ！": "Win, we need to hurry!",
"ムダなまでにバカデカい、オマエのその誇り…": "Your pride, absurdly and stupidly huge...",
"………そうかい。": ".........Is that so.",
"この戦いは、もうお前の戦いだ…": "This battle is already yours...",
"まるで、俺みたいだぜ…！": "Just like me...!",
"10ターンだ…　うん、そのくらいが限界かな？": "Ten turns... yeah, that's about my limit.",
"私は忙しいので10ターンだけ遊んであげます！": "I'm busy, so I'll play with you for only ten turns!",
"…ふざけやがって　ウィン、行くぞ！": "...You've got nerve. Win, let's go!",
"なんだこいつ…　変身…したのか…！？": "What is this... it... transformed...!?",
"ふうううううんんんむううぅぅ……": "Hmmmhmmm......",
"こいつ…わざと魔法を使わないようにして…": "This guy... deliberately avoiding magic...",
"俺たちと遊んでいるのか…！！": "he's toying with us...!!",
"私は魔法使いなのでーーーー": "I am a magic user, so—",
"うっかりしてたまに魔法を使っちゃうかも": "I might accidentally use magic sometimes—",
"知れないけれど………": "I can't be sure, though......",
"おおめにみていただきたい！！！": "please look the other way!!!",
"はいはいはい、頑張ってくださいキミたちー": "Okay okay, do your best, you lot~",
"そろそろ時間切れだよ？しめきりでーーーーす": "Time's almost up, okay? It's the deadline~",
"ウィン…　": "Win...",
"10ターン以内にこいつを倒せると思うか…？": "Think we can beat him within ten turns...?",
"ピケピケの身体から猛烈な闇の波動が放たれる！！": "A violent wave of Dark energy bursts from Pikepike!!",
"あ…　ごめん…　ちょっと厳しい…": "Ah... sorry... this is a bit tough...",
"魔法使っていいかなああああああ！！！？？": "Can I please use magic—!!!??",
"はいはいざんねん、お時間で――――す！！": "Okay okay, too bad, time's up—!!",
"あーしんどい、ちょっとはしゃぎ過ぎた…": "Ah, tiring... I got a bit too carried away...",
"こいつも人食いの…ドッグ？": "This one's a man-eating... dog?",
"ドッグなのか、これは…！？": "Is this thing a dog...!?",
"ジャクリーン：": "Jacqueline:",
"フゥううゥゥぉぉおおおおおあああッ！！": "Fuuuuooooooh!!",
"うお！？　なんだソレ…？": "Whoa!? What's that...?",
"ま、まあ大丈夫だろ…！！": "W-Well, it'll be fine...!!",
"こいつも人食いの…イヌ？　イヌなのか！？": "This one's a man-eating... dog? Is it a dog!?",
}

PATH = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "..",
                                     "docs", "text", "batches", "troop.tsv"))


def norm(s):
    return re.sub(r"[ \u3000]+", " ", s).strip()


def main():
    keyed = {norm(k): v for k, v in D.items()}
    with open(PATH, encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh, delimiter="\t"))
    filled = 0
    for r in rows:
        if (r.get("translation") or "").strip():
            continue
        t = keyed.get(norm(r["japanese"]))
        if t:
            r["translation"] = t
            filled += 1
    with open(PATH, "w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=["id", "japanese", "translation"],
                           delimiter="\t")
        w.writeheader()
        w.writerows(rows)
    print("troop.tsv filled", filled, "remaining",
          sum(1 for r in rows if not (r.get("translation") or "").strip()))


if __name__ == "__main__":
    main()
