#!/usr/bin/env python3
"""Fill batch 60: battle log messages (skills, states, boss scenes).

Particles: leading は/を -> " ...", leading の -> "'s ...".
"""
import csv
import os
import re

D = {
"はフェイントで敵を惑わして突いた！": " feints to confuse the enemy, then thrusts!",
"のすばやい攻撃！": "'s swift attack!",
"はダークヒールの魔法を発動した！": " casts the Dark Heal spell!",
"はダークサンダーの魔法を発動！": " casts the Dark Thunder spell!",
"黒いいなずまが　ウィンたちに降り注ぐ！": "Black lightning rains down upon the party!",
"はダフィールファイアの魔法を発動！": " casts the Dafill Fire spell!",
"はダフィールファイアストームを発動！": " casts Dafill Firestorm!",
"は懐に飛び込んできた！": " closes in!",
"の手のひらに澄んだ薬水が湧き出た！": "'s palm wells up with clear medicinal water!",
"はダークバリアの魔法を発動した！": " casts the Dark Barrier spell!",
"魔法を吸い込む穴が現れた！": "A hole that devours magic appears!",
"はダークブリザードを発動！": " casts Dark Blizzard!",
"はダークファイアの魔法を発動！": " casts the Dark Fire spell!",
"暗く燃え盛る炎が　ウィンたちを襲う！": "Dark, blazing flames assault the party!",
"目の前が何も見えないまま焼かれる！！": "You are burned, unable to see anything!!",
"は黒くかがやく光線を放った！": " fires a darkly shining beam!",
"は%1を唱えた！": " chants %1!",
"がミケーネブリザードを発動！！": " activates Mycenae Blizzard!!",
"のミケーネバリア！！": "'s Mycenae Barrier!!",
"はホノオの足元を狙って振り回してきた！": " swings at Hono's feet!",
"ホノオはタイミング合わせてジャンプした！": "Hono times it and jumps!",
"は気合を溜めて武器を振り下ろした！": " focuses its spirit and brings its weapon down!",
"はこの一撃に賭けた…　『流し斬り！』": " stakes everything on this strike... \"Flowing Slash!\"",
"は水の紋章を高くかかげた！": " raises the Water Crest high!",
"マンキンタンの魔法が発動！！": "The Mankintan spell activates!!",
"とてつもない冷気が　ウィンたちを襲う！！": "A tremendous chill assails the party!!",
"突然巨大な津波が現れた…！！": "A colossal tsunami suddenly appears...!!",
"は物凄い勢いで突進してきた！": " charges with tremendous force!",
"は毒の牙で噛みついてきた！": " bites with venomous fangs!",
"は大きく振りかぶって攻撃してきた！": " winds up and attacks!",
"イヤシの魔法が発動！": "The Heal spell activates!",
"の攻撃！": "'s attack!",
"青龍はミケーネを攻撃した！": "Seiryu attacks Mycenae!",
"は恐ろしい叫び声をあげた！": " lets out a terrifying cry!",
"はフェイントでウィンを惑わして突いた！": " feints to confuse Win, then thrusts!",
"は深い眠りに落ちた！": " falls into a deep sleep!",
"の身体は強力な毒におかされた！": "'s body is stricken with powerful poison!",
"は反撃の構えを取った！！": " assumes a counter stance!!",
"の身体は毒におかされた！": "'s body is stricken with poison!",
"は我に返った！": " snaps back to its senses!",
"はパニック状態に陥った！": " falls into a panic!",
"の燃える闘志が奇跡を起こす！": "'s burning fighting spirit works a miracle!",
"ドコンジョウの魔法が発動！": "The Guts spell activates!",
"はダークウィングの魔法を発動した！": " casts the Dark Wing spell!",
"ピケピケの素早さが２倍になる！": "Pikepike's agility doubles!",
"漆黒のふぶきが、ウィンたちを襲う！": "A jet-black blizzard assails the party!",
"はダークフレイムの魔法を発動！": " casts the Dark Flame spell!",
"はツナミの魔法を発動した！": " casts the Tsunami spell!",
"しかし、ミケーネブリザードで相殺される！！": "But it is canceled out by Mycenae Blizzard!!",
"はミケーネビームを放った！！": " fires the Mycenae Beam!!",
"ナガレは防いだが、すごい衝撃だ！！": "Nagare blocks it, but the impact is immense!!",
"しかし、ナガレはツナミを放ち、相殺した！！": "But Nagare unleashes a Tsunami and cancels it out!!",
"『はあああああ！！』": "\"Haaaaaah!!\"",
"ミケーネは鉄のムチを振り回した！！": "Mycenae swings an iron whip!!",
"『そこーーッ！！』": "\"There—!!\"",
"ミケーネは鋭くムチをしならせた！！": "Mycenae cracks her whip sharply!!",
"『足元がお留守だよ！！』": "\"Your feet are wide open!!\"",
"鉄のムチが、ナガレの足元を狙う！！": "The iron whip strikes at Nagare's feet!!",
"ミケーネの身体を氷の鎧が包み込む！！": "An armor of ice envelops Mycenae!!",
"はホノオの頭部を狙った！！": " aims at Hono's head!!",
"は走り込みながら剣を大きく薙ぎ払った！": " charges in, sweeping its sword in a wide arc!",
"は素早く武器を振り回した！": " whirls its weapon swiftly!",
"『隙あり…！！』": "\"An opening...!!\"",
"ホノオの反応が間に合わない！": "Hono can't react in time!",
"巨大な火の玉が襲ってくる…！！": "A colossal fireball comes hurtling...!!",
"何もかもを焼き尽くす熱風が襲ってくる…！！": "A scorching wind that burns all comes sweeping in...!!",
"は両手の燃える剣で攻撃した！": " attacks with twin flaming swords!",
"はふわりとジャンプした！": " leaps lightly!",
"そして怒涛の連続斬りを放った！！": "Then unleashes a torrent of slashes!!",
"は一瞬の隙をついて敵の懐に飛び込んだ！": " seizes a momentary opening and closes in!",
"ピピン『バクハツ！！』　相殺で威力が弱まる！！": "Pipin: \"Explosion!!\" The clash weakens its power!!",
"ピピン『ツナミ！！』　相殺で威力が弱まった！！": "Pipin: \"Tsunami!!\" The clash weakens its power!!",
"テッペキの魔法！見えない壁がピピンたちを守る！": "Iron Wall! An invisible barrier shields Pipin's group!",
"『マンキンタン！！』": "\"Mankintan!!\"",
"しかし、ピピンはツナミを放ち、相殺した！！": "But Pipin unleashes a Tsunami and cancels it out!!",
"ダフィールの身体を氷の鎧が包み込む！！": "An armor of ice envelops Dafill!!",
"はウロチョロと周りを走り回った！": " scurries around restlessly!",
"はベノムシャワーを発動！": " activates Venom Shower!",
"毒の液体が霧状になって襲い来る！！": "Venomous liquid attacks in a mist!!",
"はダフィールフレアーを発動！": " activates Dafill Flare!",
"突然の爆発に防ぐ手段がない…！！": "There is no way to guard against the sudden explosion...!!",
"はダークストームを発動！": " activates Dark Storm!",
"何も見えないまま闇の刃に切り刻まれる…！！": "Unable to see, you are slashed by blades of darkness...!!",
"の凄まじい連続攻撃！！": "'s ferocious combo attack!!",
"は巨大な尾で攻撃してきた！！": " attacks with its colossal tail!!",
"ガードの上から吹き飛ばされる…！！": "You are blasted away, guard and all...!!",
"はカマイタチを発動！さらに！": " activates Kamaitachi! And then!",
"ピピンがフェイント突きで攻撃した！！！": "Pipin attacks with Feint Thrust!!!",
"『ウィン！カマカゼだ！！』": "\"Win! Kamakaze!!\"",
"カマイタチとピピンの同時攻撃！！": "A simultaneous strike by Kamaitachi and Pipin!!",
"はピピンの剣にイカヅチを放った！！": " strikes Pipin's sword with Thunderclap!!",
"ピピンの剣が稲妻の速度で敵を切り刻む！！": "Pipin's blade, swift as lightning, carves into the enemy!!",
"がふわりと宙に浮いた！": " floats lightly into the air!",
"イカヅチの剣が敵を切り刻む！！": "The Thunderclap blade carves into the enemy!!",
"は勢いよく噛みついてきた！": " bites hard!",
"は頭上に雷雲を呼び出した…！！": " summons a storm cloud overhead...!!",
"ツナミに合わせてイカヅチが落ちる！！": "Thunderclap strikes in tandem with the Tsunami!!",
"『ツナミ…！』敵を水浸しにした！": "\"Tsunami...!\" The enemy is drenched!",
"そこへウィンのイカヅチが落ちる…！！": "Then Win's Thunderclap comes crashing down...!!",
"はミケーネブリザードを発動した！！": " activates Mycenae Blizzard!!",
"「最大出力よ…ッ！！」": "\"Maximum output...!!\"",
"最大出力のミケーネブリザードが発動…！！": "A maximum-output Mycenae Blizzard activates...!!",
"巨大な火の玉が飛んでくる…！！": "A colossal fireball comes flying...!!",
"猛烈な熱風がウィンたちを襲う…！！": "A violent heat wave assails the party...!!",
"は鎌を振り回した！": " whirls a scythe!",
"は足元を狙って鎌を振り払ってきた！": " swings its scythe at your feet!",
"はツナミの魔法を発動した！！": " activates the Tsunami spell!!",
"は鋭い爪を振りかざした！": " raises sharp claws!",
"はハヤテの魔法を発動した！": " activates the Hayate spell!",
"はカマイタチの魔法を発動した！": " activates the Kamaitachi spell!",
"足元をカマイタチが襲う！": "A Kamaitachi strikes at your feet!",
"はイカヅチの魔法を発動した！！": " activates the Thunderclap spell!!",
"巨大なイナズマが発生した…！！": "A colossal bolt of lightning forms...!!",
"は猛毒の牙で噛みついてきた！": " bites with deadly-venom fangs!",
"は走り込みながら刀を大きく薙ぎ払った！": " charges in, sweeping its blade in a wide arc!",
"は狂戦士の舞を踊った！": " dances the berserker dance!",
"味方全体の攻撃力が２倍にアップした！！": "The whole party's attack power doubles!!",
"はソードブレイカーを発動！": " activates Sword Breaker!",
"短刀がこちらの武器を絡めとる！": "A dagger entangles your weapon!",
"腹部への攻撃だ！": "An attack to the abdomen!",
"はウロチョロと周りを飛び回った！": " flits around restlessly!",
"は走り込んできた！！": " charges in!!",
"擦れ違いざま急所を狙ってくる！！": "It aims for a vital spot as it passes!!",
"目くらまし攻撃だ！": "A blinding attack!",
"は身を隠した…　": " hides itself...",
"そして背後から襲い掛かってきた！！": "Then strikes from behind!!",
"は　黒い風を　その身体にまとった…！": " wraps itself in a black wind...!",
"はヒールポーションを取り出した！": " pulls out a Heal Potion!",
"がぶ飲みしている！！": "and gulps it down!!",
"狙いはこちらの足元だ！！": "The target is your feet!!",
"はネバネバした糸を吐き出した！": " spits sticky webbing!",
"は%1を放った！": " unleashes %1!",
"は敵の足元を狙って槍を振り払った！": " sweeps its spear at the enemy's feet!",
"『秘剣！つばめ返し！！』": "\"Secret art! Swallow Reversal!!\"",
"は気合を溜めて大剣を振り下ろした！": " focuses its spirit and brings its great sword down!",
"は毒の針で突き刺してきた！": " stabs with a poisoned needle!",
"は眠りの花粉を吹き出した！": " blows out sleep pollen!",
"は隙をついて敵の懐に飛び込んできた！": " seizes an opening and closes in!",
"は足元を狙って槍を振り払ってきた！": " sweeps its spear at your feet!",
"は敵の急所へ鋭く突きあげた！": " thrusts sharply at the enemy's vitals!",
"敵は防御が間に合わない！": "The enemy can't defend in time!",
"は身の守りを固めた！": " hardens its guard!",
"は風の紋章を高くかかげた！": " raises the Wind Crest high!",
"ハヤテの魔法が発動！": "The Hayate spell activates!",
"は左腕を振り下ろした！": " swings its left arm down!",
"敵の足元をカマイタチが襲う！": "A Kamaitachi strikes at the enemy's feet!",
"は足元を狙って武器を振り回してきた！": " whirls its weapon at your feet!",
"は突然素早く攻撃してきた！": " suddenly attacks with blinding speed!",
"は左拳を眼前で握りしめた！": " clenches its left fist before your eyes!",
"敵の中心で爆発が起こった！": "An explosion erupts at the enemy's center!",
"は火の紋章を高くかかげた！": " raises the Fire Crest high!",
"狂戦士の魔法が発動！力が溢れてくる！": "The Berserker spell activates! Power surges forth!",
"は敵の脳天めがけて武器を振り下ろした！": " brings its weapon down on the enemy's crown!",
"は踊るように回転して剣を振り回した！": " spins and whirls its sword as if dancing!",
"は炎をまとった刀を振りかざした！": " raises a flame-wreathed blade!",
"は雷をまとった刀を振りかざした！": " raises a lightning-wreathed blade!",
"は氷をまとった刀を振りかざした！": " raises an ice-wreathed blade!",
"はジンダイコの魔法を放った！": " casts the Jindaiko spell!",
"はテッペキの魔法を放った！": " casts the Iron Wall spell!",
"はシップウの魔法を放った！": " casts the Gale spell!",
"は大きく薙ぎ払った！": " sweeps wide!",
"はイノチの魔法を発動！": " activates the Life spell!",
"倒れた味方を優しい光が包み込む…": "A gentle light envelops the fallen ally...",
"テッペキの魔法！見えない壁が現れた！": "Iron Wall! An invisible barrier appears!",
"は鉄のムチを振り回した！": " swings an iron whip!",
"黒いふぶきが、ウィンたちを襲う！": "A black blizzard assails the party!",
"は砂煙を巻き上げた！": " kicks up a cloud of sand!",
"視界がふさがれていく…！": "Your vision is being blocked...!",
"は激しいふぶきを呼び出した！": " summons a fierce blizzard!",
"『青龍よ！やっておしまい！！』": "\"Seiryu! Finish them off!!\"",
"『いきなさい！青龍よ！』": "\"Go! Seiryu!\"",
"は剣としっぽを振り回した！": " whirls its sword and tail!",
"は足にしがみついてきた！": " clings to your leg!",
"は凄まじい連続攻撃をしてきた！！": " unleashes a ferocious combo attack!!",
"しかしホノオはその気配を感じ取っている！": "But Hono senses the attack!",
"の気絶攻撃がホノオの頭部を襲う！": "'s Stun Attack strikes at Hono's head!",
"ホノオはすばやく身体の位置をずらした！": "Hono swiftly shifts his body out of the way!",
"の気合を溜めた攻撃！": "'s spirit-charged attack!",
"ホノオ『こっちも気合で避ける…！！』": "Hono: \"I'll dodge with spirit too...!!\"",
"は逃げてしまった。": " fled.",
"は医療キットを取り出した！": " pulls out a Medical Kit!",
"はショックポーションを取り出した！": " pulls out a Shock Potion!",
"しかし、ウィンは惑わされない！": "But Win is not fooled!",
"はウィンの脳天めがけて振り下ろした！": " brings its weapon down on Win's crown!",
"ウィンはすばやく身体の位置をずらした！": "Win swiftly shifts his body out of the way!",
"はカマイタチの魔法を発動！": " activates the Kamaitachi spell!",
"しかしウィンには迷いがある…！": "But Win hesitates...!",
"は　自分自身を攻撃した…！": " attacks itself...!",
"は様子を見ている。": " watches the situation.",
"は左手を高くかかげた！": " raises its left hand high!",
"疾風がウィンたちの身体を包んだ！": "A gale wraps itself around the party!",
"の風の紋章が頭上に雷雲を呼ぶ…！": "'s Wind Crest summons a storm cloud overhead...!",
"巨大なイナズマが発生し敵に落ちた！": "A colossal bolt of lightning forms and strikes the enemy!",
"は左拳を強く握りしめた…！": " clenches its left fist tightly...!",
"敵の中心で大爆発が起こる…！！": "A great explosion erupts at the enemy's center...!!",
"は敵に背を向け、左手を宙へかかげた…": " turns its back to the enemy and raises its left hand skyward...",
"たちの頭上から薬水の雨が降り注ぐ！": "'s heads are blessed with a rain of medicinal water!",
"イヤシノアメの魔法が発動！": "The Healing Rain spell activates!",
"は熱く燃える息を吐いた！": " breathes a blazing hot breath!",
"は心地よい歌声で歌った！": " sings a soothing melody!",
"眠くなってくる…！": "You grow drowsy...!",
"は弓で毒の矢を放ってきた！": " fires a poisoned arrow from its bow!",
"『まーんきーんたーん！！』": "\"Maaankiintaan!!\"",
"は恐ろしい叫び声を上げた！！": " lets out a terrifying scream!!",
"は敵の武器を狙って突いた！": " thrusts at the enemy's weapon!",
"マンゴーシュが敵の武器を絡めとる！": "The Main Gauche entangles the enemy's weapon!",
"は剣を垂直に構え…　とつぜん突いた！": " holds its sword vertical... then thrusts without warning!",
"目にも止まらぬ速さで連続突きを繰り出す！！": "It unleashes a blur of successive thrusts!!",
"は武器を頭上で大きく回転させた…": " whirls its weapon overhead...",
"敵集団を凄まじい勢いで切り刻む！！": "It carves through the enemy ranks with ferocious force!!",
"は身を隠して敵集団の裏に回った…": " hides and circles behind the enemy ranks...",
"隙を突いて敵集団の背後から襲い掛かった！！": "Seizing an opening, it strikes from behind!!",
"『真！つばめ返し！！』": "\"True! Swallow Reversal!!\"",
"は回転する刃を振り回した！": " whirls a spinning blade!",
"戦場が激しい金属の擦れる音で満たされる！": "The battlefield fills with the screech of grinding metal!",
"は暗くかがやくブレスを吐いた！": " breathes a darkly shining breath!",
"は眠り続けている。": " keeps sleeping.",
"は目を覚ました！": " wakes up!",
"の身体から猛毒が消えさった！": "'s deadly venom fades away!",
"は転倒した！": " is knocked down!",
"は地面に倒れた！": " falls to the ground!",
"は起き上がれない！": " cannot get up!",
"は起き上がった！": " gets back up!",
"は気絶してしまった！": " is knocked unconscious!",
"は気絶した！": " is stunned!",
"は気絶している！": " is unconscious!",
"は意識を回復した！": " regains consciousness!",
"の魔力が暴走！！魔力が二倍になった！！": "'s magic runs wild!! Magic power doubles!!",
"の魔力は暴走している！！": "'s magic is running wild!!",
"は反撃の構えを取っている！！": " is poised to counter!!",
"はスキのない構えを取っている！！": " stands in a flawless guard!!",
"は倒れた！": " has fallen!",
"を倒した！": " has been defeated!",
"は立ち上がった！": " gets back up!",
"の身体から毒が消えさった！": "'s poison fades away!",
"は暗闇に閉ざされた！": " is shrouded in darkness!",
"を暗闇に閉ざした！": " has been shrouded in darkness!",
"の暗闇が消えた！": "'s darkness fades away!",
"は言葉を発せなくなった！": " is silenced!",
"の魔法を封じた！": "'s magic has been sealed!",
"の沈黙が解けた！": "'s silence lifts!",
"は怒りに我を忘れた！": " flies into a rage!",
"を激しく怒らせた！": " has been driven into a rage!",
"は冷静さを取り戻した！": " regains its composure!",
"は操られてしまった！": " has been controlled!",
"を操った！": " has been controlled!",
}

PATH = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "..",
                                     "docs", "text", "batches", "battle.tsv"))


def norm(s):
    return re.sub(r"[ \u3000]+", " ", s).strip().replace("\\", "\")


def main():
    keyed = {norm(k): v for k, v in D.items()}
    with open(PATH, encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh, delimiter="\t"))
    filled = 0
    for r in rows:
        if (r.get("translation") or "").strip():
            continue
        t = keyed.get(norm(r["japanese"]))
        if t:
            r["translation"] = t
            filled += 1
    with open(PATH, "w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=["id", "japanese", "translation"],
                           delimiter="\t")
        w.writeheader()
        w.writerows(rows)
    print("battle.tsv filled", filled, "remaining",
          sum(1 for r in rows if not (r.get("translation") or "").strip()))


if __name__ == "__main__":
    main()
