#!/usr/bin/env python3
"""Fill batch 02: database description strings (armors/items/skills/weapons)."""
import csv
import os

D = {
# --- Armors ---
"DB_Armors_1_description": "A small, light shield. Rather than blocking enemy attacks, it's meant to deflect them.\nSlightly raises defense and evasion.",
"DB_Armors_2_description": "A small, light shield. Rather than blocking enemy attacks, it's meant to deflect them.\nSlightly raises defense and evasion.",
"DB_Armors_3_description": "A small, light shield. Rather than blocking enemy attacks, it's meant to deflect them.\nSlightly raises defense and evasion.",
"DB_Armors_20_description": "A small, light shield. Rather than blocking enemy attacks, it's meant to deflect them.\nSlightly raises defense and evasion.",
"DB_Armors_4_description": "An iron shield that fully blocks slashes and arrows, and stops heavy blows to a degree.\nRaises defense and slightly raises evasion, but lowers agility.",
"DB_Armors_5_description": "An iron shield that fully blocks slashes and arrows, and stops heavy blows to a degree.\nRaises defense and slightly raises evasion, but lowers agility.",
"DB_Armors_6_description": "An iron shield that fully blocks slashes and arrows, and stops heavy blows to a degree.\nRaises defense and slightly raises evasion, but lowers agility.",
"DB_Armors_21_description": "An iron shield that fully blocks slashes and arrows, and stops heavy blows to a degree.\nRaises defense and slightly raises evasion, but lowers agility.",
"DB_Armors_7_description": "Worn mainly by Windam Kingdom soldiers in posts that don't require heavy armor.\nLight, yet sturdily made.",
"DB_Armors_8_description": "Fine clothing worn by many citizens of the Flame Kingdom as everyday wear.\nBoth breathable and durable.",
"DB_Armors_9_description": "A full set of clothing worn by the people of Seiryu when setting out on long journeys.\nEasy to move in, and excellent at keeping out the cold.",
"DB_Armors_10_description": "Light combat armor woven from fine chain. The most common armor, balancing lightness\nwith resistance to slashes. Slightly lowers agility.",
"DB_Armors_11_description": "Light combat armor woven from fine chain. The most common armor, balancing lightness\nwith resistance to slashes. Slightly lowers agility.",
"DB_Armors_12_description": "Light combat armor woven from fine chain. The most common armor, balancing lightness\nwith resistance to slashes. Lowers agility.",
"DB_Armors_22_description": "Light combat armor woven from fine chain. The most common armor, balancing lightness\nwith resistance to slashes. Lowers agility.",
"DB_Armors_13_description": "Full-body armor covering every inch of the body in metal. Very expensive,\nand its weight greatly lowers agility.",
"DB_Armors_14_description": "Full-body armor covering every inch of the body in metal. Very expensive,\nand its weight greatly lowers agility.",
"DB_Armors_15_description": "Full-body armor covering every inch of the body in metal. Very expensive,\nand its weight greatly lowers agility.",
"DB_Armors_23_description": "Full-body armor covering every inch of the body in metal. Very expensive,\nand its weight greatly lowers agility.",
"DB_Armors_16_description": "A magnificent cape issued only to knights of the Windam Knight Order.\nIt's said to hold the power of wind, though the truth is unclear.",
"DB_Armors_17_description": "A bandana made from the sash worn by the Flame Kingdom's prince, said to have died young.\nTo Hono, it's her brother's keepsake.",
"DB_Armors_18_description": "A legendary robe handed down in Seiryu since ancient times to the inheritor of the\nWater Crest. Said to have been granted by a dragon.",
"DB_Armors_19_description": "A magnificent cape issued only to the Windam Knight Captain.\nIt's said to hold the power of wind, though the truth is unclear.",
"DB_Armors_24_description": "A shield imbued with magical power.\nSlightly raises defense and evasion, and greatly raises magic defense.",
"DB_Armors_25_description": "Full-body armor covering every inch of the body in metal. A magnificent, sturdy suit\nunseen even in other nations, let alone the knight orders. Win only.",
"DB_Armors_26_description": "A legendary suit of Flame armor said to have belonged to the first King Flame.\nLight and easy to move in, yet every vital is protected. Hono only.",
"DB_Armors_27_description": "A beautiful suit of armor with a design never seen before. Ornate yet light,\nand stoutly built. Slightly lowers agility. Nagare only.",
# --- Items ---
"DB_Items_1_description": "An emergency salve made by blending several plants with medicinal properties.\nThe most widespread medicine for treating wounds. Restores 500 HP.",
"DB_Items_2_description": "A set of medical supplies issued to soldiers.\nDesigned for immediate use on the battlefield. Restores 1000 HP.",
"DB_Items_3_description": "A precious medicine made through specialized alchemy. Its ingredients are secret,\nand mass production is impossible. Restores 2000 HP.",
"DB_Items_4_description": "A pill combining the effects of an antidote and eyedrops. A specialty of the western\nland of Seiryu. Its reliable efficacy makes it popular across the continent.",
"DB_Items_5_description": "A draught that cures every status ailment except poison.\nA powerful restorative made through alchemy.",
"DB_Items_6_description": "An extremely strong liquor produced in Flame. It's only served at festivals and\nrituals, because people sometimes die. Oddly enough, it cures deadly poison.",
"DB_Items_7_description": "A gem excavated only extremely rarely in Seiryu. Legend says praying while gripping\nit revives the dead. Revives one ally.",
"DB_Items_8_description": "A draught that dispels fatigue and drowsiness, temporarily filling one with vigor.\nAn alchemist's flagship product, though some whisper regular use is dangerous.\nRestores 500 EP.",
"DB_Items_9_description": "A powerful restorative made through alchemy. Instantly revives one from stun or\ncardiac arrest, though there are rumors of aftereffects...",
"DB_Items_10_description": "A strange book given by Gada, an antiquarian of Flame. Thick, with a sturdy\nbinding, and it looks rather new.",
"DB_Items_11_description": "A mushroom consumed by Flame warriors before heading into battle.\nDoubles attack power for 10 turns!!",
"DB_Items_12_description": "A portable food unique to Seiryu. Nutritious and easy to carry,\nand favored for travel and war. Restores 500 HP.",
"DB_Items_13_description": "Fur, bones, horns, fangs, and more collected from monsters—of middling quality.\nTown shops will buy them for 100G.",
"DB_Items_14_description": "Fur, bones, horns, fangs, and more collected from monsters—in good condition.\nTown shops will buy them for 300G.",
"DB_Items_15_description": "Fur, bones, horns, fangs, and more collected from monsters—of the precious kind.\nTown shops will buy them for 600G.",
"DB_Items_16_description": "Fur, bones, horns, fangs, and more collected from monsters—of the highest grade.\nTown shops will buy them for 1000G.",
"DB_Items_17_description": "Bread made within Windam Castle, a staple of the soldiers.\nHard and dry, but plenty nutritious. Restores 300 HP.",
"DB_Items_18_description": "Delicious bread from the famous bakery of Windam Castle Town.\nCrisp outside, fluffy inside. Restores 800 HP.",
"DB_Items_20_description": "Gems, precious metals, and ornaments taken from enemies—of decent quality.\nTown shops will buy them for 100G.",
"DB_Items_21_description": "Gems, precious metals, and ornaments taken from enemies—in good condition.\nTown shops will buy them for 300G.",
"DB_Items_22_description": "Gems, precious metals, and ornaments taken from enemies—of the expensive kind.\nTown shops will buy them for 600G.",
"DB_Items_23_description": "Gems, precious metals, and ornaments taken from enemies—of the highest grade.\nTown shops will buy them for 1000G.",
"DB_Items_24_description": "Gems, precious metals, and ornaments taken from enemies—of legendary quality.\nTown shops will buy them for 100000G.",
"DB_Items_25_description": "Holding this allows entry into the Flame Kingdom.\nA gift from the king to Win.",
"DB_Items_26_description": "A sweet food made in the Flame Kingdom. Some kind of fruit,\ndried and preserved. Restores 300 HP.",
"DB_Items_27_description": "A glowing, mysterious stone that grants power when clutched.\nUsing it raises attack by 5.",
"DB_Items_28_description": "A glowing, mysterious stone that grants power when clutched.\nUsing it raises defense by 5.",
"DB_Items_29_description": "A glowing, mysterious stone that grants power when clutched.\nUsing it raises agility by 5.",
"DB_Items_30_description": "A glowing, mysterious stone that grants power when clutched.\nUsing it raises magic attack by 5.",
"DB_Items_31_description": "A glowing, mysterious stone that grants power when clutched.\nUsing it raises magic defense by 5.",
"DB_Items_32_description": "A glowing, mysterious stone that grants power when clutched.\nUsing it raises Max HP by 200.",
"DB_Items_33_description": "A glowing, mysterious stone that grants power when clutched.\nUsing it raises Max EP by 50.",
"DB_Items_34_description": "A glowing, mysterious stone that grants power when clutched.\nUsing it raises agility by 5 and Max EP by 50.",
"DB_Items_35_description": "A glowing, mysterious stone that grants power when clutched.\nUsing it raises attack by 5 and magic attack by 5.",
"DB_Items_36_description": "A glowing, mysterious stone that grants power when clutched.\nUsing it raises Max HP by 200 and magic defense by 5.",
"DB_Items_37_description": "The evolved form of the rice ball. Nutritious and easy to carry,\nand favored for travel and war. Restores 1200 HP.",
"DB_Items_38_description": "A set of medical supplies issued to soldiers.\nDesigned for immediate use on the battlefield. Restores 1500 HP.",
"DB_Items_40_description": "Fur, bones, horns, fangs, and more collected from monsters—of the highest grade.\nTown shops will buy them for 3000G.",
"DB_Items_41_description": "A glowing, mysterious stone that grants power when clutched.\nUsing it raises all abilities.",
# --- Skills ---
"DB_Skills_8_description": "Water magic. Uses the power of the crest to create healing water.\nRestores about 800 HP to one ally. Costs 10 EP.",
"DB_Skills_48_description": "Water magic. Uses the power of the crest to create healing water.\nRestores about 800 HP to one ally. Costs 10 EP.",
"DB_Skills_58_description": "Water magic. Uses the power of the crest to create healing water.\nRestores about 800 HP to one ally. Costs 10 EP.",
"DB_Skills_70_description": "Water magic. Uses the power of the crest to create healing water.\nRestores about 800 HP to one ally. Costs 10 EP.",
"DB_Skills_72_description": "Water magic. Uses the power of the crest to create healing water.\nRestores about 800 HP to one ally. Costs 10 EP.",
"DB_Skills_102_description": "Water magic. Uses the power of the crest to create healing water.\nRestores about 800 HP to one ally. Costs 10 EP.",
"DB_Skills_132_description": "Water magic. Uses the power of the crest to create healing water.\nRestores about 800 HP to one ally. Costs 10 EP.",
"DB_Skills_135_description": "Water magic. Uses the power of the crest to create healing water.\nRestores about 800 HP to one ally. Costs 10 EP.",
"DB_Skills_11_description": "Runs into the enemy group while swinging the weapon around. Weaker than a normal\nattack. A straight sword and curved sword skill. Costs 9 SP.",
"DB_Skills_47_description": "Runs into the enemy group while swinging the weapon around. Weaker than a normal\nattack. A straight sword and curved sword skill. Costs 9 SP.",
"DB_Skills_13_description": "Charges into the enemy group, swinging a large weapon around.\nWeaker than a normal attack. A straight sword and curved sword skill.",
"DB_Skills_12_description": "A precise thrust that pierces enemy vitals and the gaps in their armor.\nIgnores defense. Costs 9 SP.",
"DB_Skills_14_description": "Attacks with the equipped weapon.",
"DB_Skills_32_description": "For enemies.",
"DB_Skills_33_description": "Attacks with the equipped weapon.",
"DB_Skills_35_description": "Charges one's spirit and brings a great sword down in a huge swing. Sometimes\nmisses, but deals about double damage. Costs 18 SP.",
"DB_Skills_68_description": "Charges one's spirit and brings a great sword down in a huge swing. Sometimes\nmisses, but deals about double damage. Costs 18 SP.",
"DB_Skills_121_description": "Charges one's spirit and brings a great sword down in a huge swing. Sometimes\nmisses, but deals about double damage. Costs 18 SP.",
"DB_Skills_36_description": "Fire magic. Suddenly causes an explosion right in front of the enemy.\nDeals about 600 damage to all enemies. Costs 15 EP.",
"DB_Skills_37_description": "Fire magic. Hot fighting spirit surges through the body. Doubles attack power,\nallowing attacks with superhuman strength. Cannot be stacked. Costs 9 EP.",
"DB_Skills_38_description": "Attacks with the equipped weapon.",
"DB_Skills_39_description": "Cuts down onto the enemy's head from directly above. The impact to the crown can\nstun for 1 turn. A straight sword and katana skill. Costs 18 SP.",
"DB_Skills_74_description": "Cuts down onto the enemy's head from directly above. The impact to the crown can\nstun for 1 turn. A straight sword and katana skill. Costs 18 SP.",
"DB_Skills_40_description": "Using the curved sword's easy handling, spins and slashes the enemy repeatedly.\nRandom 4 hits. Costs 18 SP.",
"DB_Skills_51_description": "Using the curved sword's easy handling, spins and slashes the enemy repeatedly.\nRandom 4 hits. Costs 18 SP.",
"DB_Skills_60_description": "Using the curved sword's easy handling, spins and slashes the enemy repeatedly.\nRandom 4 hits. Costs 18 SP.",
"DB_Skills_113_description": "Using the curved sword's easy handling, spins and slashes the enemy repeatedly.\nRandom 4 hits. Costs 18 SP.",
"DB_Skills_114_description": "Using the curved sword's easy handling, spins and slashes the enemy repeatedly.\nRandom 4 hits. Costs 18 SP.",
"DB_Skills_115_description": "Using the curved sword's easy handling, spins and slashes the enemy repeatedly.\nRandom 4 hits. Costs 18 SP.",
"DB_Skills_41_description": "Attacks with the equipped weapon.",
"DB_Skills_42_description": "Attacks with the equipped weapon.",
"DB_Skills_43_description": "Attacks with the equipped weapon.",
"DB_Skills_49_description": "Water magic. Uses the power of the crest to revive one fallen ally.\nCosts 30 EP.",
"DB_Skills_50_description": "Water magic. An invisible wall of flowing water deflects physical attacks.\nRaises the whole party's defense by 50%. Can stack up to twice. Costs 15 EP.",
"DB_Skills_62_description": "Attacks with the equipped weapon.",
"DB_Skills_66_description": "Attacks with the equipped weapon.",
"DB_Skills_67_description": "For enemies.",
"DB_Skills_71_description": "A thrust that confuses the enemy with deft swordplay and strikes the opening it\ncreates. Ignores defense and lowers the enemy's defense. A dagger and rapier\nskill. Costs 20 SP.",
"DB_Skills_73_description": "A thrust that confuses the enemy with deft swordplay and strikes the opening it\ncreates. Ignores defense and lowers the enemy's defense. A dagger and rapier\nskill. Costs 20 SP.",
"DB_Skills_77_description": "A thrust that confuses the enemy with deft swordplay and strikes the opening it\ncreates. Ignores defense and lowers the enemy's defense. A dagger and rapier\nskill. Costs 20 SP.",
"DB_Skills_128_description": "A thrust that confuses the enemy with deft swordplay and strikes the opening it\ncreates. Ignores defense and lowers the enemy's defense. Costs 20 SP.",
"DB_Skills_75_description": "Wind magic. Sharp blades of vacuum tear at the enemy's feet.\nDeals about 800 damage to one enemy and lowers agility. Costs 18 EP.",
"DB_Skills_80_description": "Wind magic. Wind wraps around the whole party, raising agility by 50%.\nStacks twice to match Hayate's speed. Costs 15 EP.",
"DB_Skills_81_description": "Wind magic. Calls a massive bolt of lightning down on the enemy... a mighty power.\nDeals about 2000 damage to one enemy and stuns. Costs 40 EP.",
"DB_Skills_82_description": "Fire magic. Causes a great explosion at the enemy's center... a mighty spell.\nDeals about 1800 damage to all enemies. Costs 60 EP.",
"DB_Skills_83_description": "Water magic. Summons a tsunami to crash down on the enemy group... a mighty spell.\nDeals about 1200 damage to all enemies. Costs 30 EP.",
"DB_Skills_110_description": "Water magic. Summons a tsunami to crash down on the enemy group... a mighty spell.\nDeals about 1200 damage to all enemies. Costs 30 EP.",
"DB_Skills_84_description": "Water magic. Uses the power of the crest to rain medicinal water over the whole\nparty. Restores about 800 HP to the whole party. Costs 20 EP.",
"DB_Skills_87_description": "Attacks with the equipped weapon.",
"DB_Skills_88_description": "Attacks with the equipped weapon.",
"DB_Skills_89_description": "Water magic. Uses the power of the crest to create water surpassing Mankintan.\nFully cures one ally of all status ailments except stun and knockdown.\nCosts 10 EP.",
"DB_Skills_134_description": "Water magic. Uses the power of the crest to create water surpassing Mankintan.\nFully cures one ally of all status ailments except stun and knockdown.\nCosts 10 EP.",
"DB_Skills_90_description": "Lets out an unbelievably terrifying shout, provoking and intimidating the whole\nenemy party. Inflicts confusion and enrage on all enemies. Costs 20 SP.",
"DB_Skills_91_description": "The defense-focused shape of the main gauche can even destroy enemy weapons.\nIgnores defense and lowers attack power. Costs 20 EP.",
"DB_Skills_92_description": "At superhuman speed, pierces three of the enemy's vitals almost simultaneously.\nIgnores defense; 3 sure-hit hits. Costs 30 SP.",
"DB_Skills_93_description": "Swings the weapon overhead while charging into the enemy group.\nDeals heavy damage to all enemies. Costs 40 SP.",
"DB_Skills_94_description": "Hides, circles behind the enemy group, and suddenly strikes.\nIgnores defense against all enemies and inflicts confusion. Costs 30 SP.",
"DB_Skills_95_description": "A secret art that breaks the enemy's defense with the first stroke and slashes\nwith the second. Deals damage ignoring half the enemy's defense and lowers it.\nCosts 40 SP.",
"DB_Skills_96_description": "A killing sword that, if it lands fully, fells the target in one blow. Legend says\nfailure costs the user their soul. Deals about double damage. Costs 25 SP.",
"DB_Skills_129_description": "A killing sword that, if it lands fully, fells the target in one blow. Legend says\nfailure costs the user their soul. Deals about double damage. Costs 25 SP.",
"DB_Skills_100_description": "Fire magic. Burning fighting spirit works a miracle and fully restores HP.\nFully restores one ally's HP. Costs 30 EP.",
"DB_Skills_109_description": "Attacks with the equipped weapon.",
"DB_Skills_111_description": "Attacks with the equipped weapon.",
"DB_Skills_118_description": "For enemies.",
"DB_Skills_119_description": "Attacks with the equipped weapon.",
"DB_Skills_122_description": "A spear thrust from near ground level that strikes at the enemy's vitals in an\ninstant. The enemy can't react in time; ignores defense. A spear skill.\nCosts 18 SP.",
"DB_Skills_127_description": "After floating lightly into the air, slashes four times quickly before landing.\n4 attacks on one enemy. Costs 20 SP.",
"DB_Skills_133_description": "Water magic. An invisible wall of flowing water deflects physical attacks.\nRaises the whole party's defense by 50%. Costs 15 EP.",
"DB_Skills_144_description": "Attacks with the equipped weapon.",
"DB_Skills_146_description": "A simultaneous attack of Kamaitachi and Feint Thrust. Deals defense-ignoring\ndamage to the enemy and lowers defense and agility. Costs 20 EP.",
"DB_Skills_147_description": "A simultaneous attack of Kamaitachi and Feint Thrust. Deals defense-ignoring\ndamage to the enemy and lowers defense and agility. Costs 20 SP.",
"DB_Skills_148_description": "Drops a thunderclap onto Pipin's sword as it floats lightly in the air, then\nslashes four times in quick succession. Deals heavy damage 4 times to one enemy.\nCosts 30 EP.",
"DB_Skills_149_description": "Drops a thunderclap onto Pipin's sword as it floats lightly in the air, then\nslashes four times in quick succession. Deals heavy damage 4 times to one enemy.\nCosts 30 SP.",
"DB_Skills_150_description": "A combo spell that soaks the enemy with a tsunami, then drops a colossal bolt of\nlightning. Deals about 5000 damage to all enemies and stuns. Costs 50 EP.",
# --- Weapons ---
"DB_Weapons_1_description": "A straight sword of forged iron. A mass-produced model widely used in Windam.\n1 skill slot. Equippable by Win and Pipin.",
"DB_Weapons_2_description": "A straight sword of forged iron. A mass-produced model widely used in Windam.\n2 skill slots. Equippable by Win and Pipin.",
"DB_Weapons_3_description": "A straight sword of forged iron. A mass-produced model widely used in Windam.\n2 skill slots. Equippable by Win and Pipin.",
"DB_Weapons_29_description": "A straight sword of forged iron. A mass-produced model widely used as gear for\nlow-ranking soldiers and for merchants' self-defense. 2 skill slots.",
"DB_Weapons_4_description": "A curved-blade sword produced in the Flame Kingdom. Slightly raises agility.\n1 skill slot. Equippable by Hono.",
"DB_Weapons_5_description": "A curved-blade sword produced in the Flame Kingdom. Slightly raises agility.\n2 skill slots. Equippable by Hono.",
"DB_Weapons_6_description": "A curved-blade sword produced in the Flame Kingdom. Slightly raises agility.\n2 skill slots. Equippable by Hono.",
"DB_Weapons_33_description": "A curved-blade sword produced in the Flame Kingdom. Slightly raises agility.\n3 skill slots. Equippable by Hono.",
"DB_Weapons_7_description": "A sharp, beautiful blade produced in Seiryu. Lowers agility but has high power.\nOccasionally counterattacks unharmed. 1 skill slot. Equipped by Nagare.",
"DB_Weapons_8_description": "A sharp, beautiful blade produced in Seiryu. Lowers agility but has high power.\nOccasionally counterattacks unharmed. 2 skill slots. Equipped by Nagare.",
"DB_Weapons_9_description": "A sharp, beautiful blade produced in Seiryu. Lowers agility but has high power.\nOccasionally counterattacks unharmed. 2 skill slots. Equipped by Nagare.",
"DB_Weapons_10_description": "A dagger for self-defense. Greatly raises critical rate and agility.\n1 skill slot. Equippable by Win, Hono and Pipin.",
"DB_Weapons_11_description": "A dagger for self-defense. Greatly raises critical rate and agility.\n1 skill slot. Equippable by Win, Hono and Pipin.",
"DB_Weapons_12_description": "A dagger for self-defense. Greatly raises critical rate and agility.\n2 skill slots. Equippable by Win, Hono and Pipin.",
"DB_Weapons_35_description": "A dagger for self-defense. Greatly raises critical rate and agility.\n3 skill slots. Equippable by Win and Hono.",
"DB_Weapons_13_description": "A slender sword specialized solely for striking enemy vitals. Raises critical rate.\n1 skill slot. Equippable by Win.",
"DB_Weapons_14_description": "A slender sword specialized solely for striking enemy vitals. Raises critical rate.\n2 skill slots. Equippable by Win.",
"DB_Weapons_15_description": "A slender sword specialized solely for striking enemy vitals. Raises critical rate.\n2 skill slots. Equippable by Win.",
"DB_Weapons_36_description": "A slender sword specialized solely for striking enemy vitals. Raises critical rate.\n3 skill slots. Equippable by Win.",
"DB_Weapons_16_description": "Strikes vitals from a distance. Lowers agility but raises critical rate.\n1 skill slot. Equippable by Win.",
"DB_Weapons_17_description": "Strikes vitals from a distance. Lowers agility but raises critical rate.\n2 skill slots. Equippable by Win.",
"DB_Weapons_18_description": "Strikes vitals from a distance. Lowers agility but raises critical rate.\n2 skill slots. Equippable by Win.",
"DB_Weapons_37_description": "Strikes vitals from a distance. Lowers agility but raises critical rate.\n3 skill slots. Equippable by Win.",
"DB_Weapons_19_description": "A massive blade. More for bludgeoning than cutting. Powerful, but greatly lowers\nagility and hit rate. 1 skill slot. Equipped by Hono.",
"DB_Weapons_20_description": "A massive blade. More for bludgeoning than cutting. Powerful, but greatly lowers\nagility and hit rate. 1 skill slot. Equipped by Hono.",
"DB_Weapons_21_description": "A massive blade. More for bludgeoning than cutting. Powerful, but greatly lowers\nagility and hit rate. 2 skill slots. Equipped by Hono.",
"DB_Weapons_38_description": "A massive blade. More for bludgeoning than cutting. Powerful, but greatly lowers\nagility and hit rate. 3 skill slots. Equipped by Hono.",
"DB_Weapons_45_description": "A massive blade. More for bludgeoning than cutting. Powerful, but greatly lowers\nagility and hit rate. 3 skill slots. Equipped by Hono.",
"DB_Weapons_50_description": "A massive blade. More for bludgeoning than cutting. Powerful, but greatly lowers\nagility and hit rate. 6 skill slots. Equipped by Hono.",
"DB_Weapons_22_description": "Used by gladiators of old. The wide blade deflects enemy attacks and raises\nevasion. 3 skill slots. Equippable by Win.",
"DB_Weapons_23_description": "A treasured sword passed down through the kings of the Flame Kingdom.\nRarely reflects magic. 3 skill slots. Equippable by Hono.",
"DB_Weapons_42_description": "A treasured sword passed down through the kings of the Flame Kingdom.\nRarely reflects magic. 3 skill slots. Equippable by Hono.",
"DB_Weapons_24_description": "A wonderfully beautiful, sturdy blade unseen in Seiryu. About the size of a\nwakizashi. Raises critical rate. 3 skill slots. For Nagare.",
"DB_Weapons_43_description": "A wonderfully beautiful, sturdy blade unseen in Seiryu. About the size of a\nwakizashi. Raises critical rate. 3 skill slots. For Nagare.",
"DB_Weapons_52_description": "A wonderfully beautiful, sturdy blade unseen in Seiryu. About the size of a long\nwakizashi. Raises critical rate. 5 skill slots. For Nagare.",
"DB_Weapons_25_description": "A defensive dagger of unusual shape. Occasionally counterattacks against enemy\nattacks. 3 skill slots. Equippable by Win and Hono.",
"DB_Weapons_26_description": "A sharp, sturdy rapier gifted by a master smith to Roi, called a genius knight.\nA famous blade, but very hard to handle. 3 skill slots. Equipped by Win.",
"DB_Weapons_39_description": "A sharp, sturdy rapier gifted by a master smith to Roi, called a genius knight.\nA famous blade, but very hard to handle. 3 skill slots. Equipped by Win.",
"DB_Weapons_27_description": "A great spear passed down in the Saxon family. Greatly raises critical rate.\n3 skill slots. Equippable by Win.",
"DB_Weapons_44_description": "A great spear passed down in the Saxon family. Greatly raises critical rate.\n3 skill slots. Equippable by Win.",
"DB_Weapons_28_description": "An unbelievably enormous great sword. Its blows are devastating, but hit rate\ndrops drastically. 3 skill slots. Equipped by Hono.",
"DB_Weapons_30_description": "An odachi made to make the most of Swallow Reversal. Greatly lowers agility,\nraises counter and critical rates. 3 skill slots. Equipped by Nagare.",
"DB_Weapons_46_description": "An odachi made to make the most of Swallow Reversal. Greatly lowers agility,\nraises counter and critical rates. 3 skill slots. Equipped by Nagare.",
"DB_Weapons_31_description": "A straight sword of forged iron. Pipin has treasured it for years. From material\nto forging, a cut above the ordinary. 5 skill slots.",
"DB_Weapons_32_description": "A straight sword of forged iron. Long and broad, so it's hard to handle.\nNo problem for a battle-hardened knight. 3 skill slots. Equipped by Win.",
"DB_Weapons_41_description": "A straight sword of forged iron. Long and broad, so it's hard to handle.\nNo problem for a battle-hardened knight. 3 skill slots. Equipped by Win.",
"DB_Weapons_34_description": "A blade a size longer and heavier than a wakizashi. Lowers agility but has high\npower. Occasionally counterattacks unharmed. 3 skill slots. Equipped by Nagare.",
"DB_Weapons_40_description": "A short sword made with Seiryu technology. A little large, but its handling is\nsuperb. A dagger anyone can equip. 3 skill slots.",
"DB_Weapons_51_description": "A short sword made with Seiryu technology. A little large, but its handling is\nsuperb. A dagger anyone can equip. 5 skill slots.",
"DB_Weapons_47_description": "A long spear imbued with the power of wind. Greatly raises critical rate.\n5 skill slots. Equippable by Win.",
"DB_Weapons_48_description": "A blade imbued with the power of water. Lowers agility, raises counter and\ncritical rates. 5 skill slots. Equippable by Nagare.",
"DB_Weapons_49_description": "A curved blade imbued with the power of flame. Raises agility and rarely\nreflects magic. 5 skill slots. Equippable by Hono.",
}

BASE = os.path.join(os.path.dirname(__file__), "..", "..", "docs", "text", "batches")
PATH = os.path.normpath(os.path.join(BASE, "description.tsv"))


def main():
    with open(PATH, encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh, delimiter="\t"))
    filled = 0
    for r in rows:
        if r["id"] in D:
            r["translation"] = D[r["id"]]
            filled += 1
    with open(PATH, "w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=["id", "japanese", "translation"],
                           delimiter="\t")
        w.writeheader()
        w.writerows(rows)
    print("description.tsv filled", filled, "/", len(rows))
    missing = [r["id"] for r in rows if r["id"] not in D]
    if missing:
        print("missing:", missing)


if __name__ == "__main__":
    main()
